// CodeCacheHost.java is auto generated by mojom_bindings_generator.py, do not edit


// Copyright 2014 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// This file is autogenerated by:
//     mojo/public/tools/bindings/mojom_bindings_generator.py
// For:
//     third_party/blink/public/mojom/loader/code_cache.mojom
//

package org.chromium.blink.mojom;


public interface CodeCacheHost extends org.chromium.mojo.bindings.Interface {



    public interface Proxy extends CodeCacheHost, org.chromium.mojo.bindings.Interface.Proxy {
    }

    Manager<CodeCacheHost, CodeCacheHost.Proxy> MANAGER = CodeCacheHost_Internal.MANAGER;


    void didGenerateCacheableMetadata(
int cacheType, org.chromium.url.mojom.Url url, org.chromium.mojo_base.mojom.Time expectedResponseTime, org.chromium.mojo_base.mojom.BigBuffer data);



    void fetchCachedCode(
int cacheType, org.chromium.url.mojom.Url url, 
FetchCachedCodeResponse callback);

    interface FetchCachedCodeResponse extends org.chromium.mojo.bindings.Callbacks.Callback2<org.chromium.mojo_base.mojom.Time, org.chromium.mojo_base.mojom.BigBuffer> { }



    void clearCodeCacheEntry(
int cacheType, org.chromium.url.mojom.Url url);



    void didGenerateCacheableMetadataInCacheStorage(
org.chromium.url.mojom.Url url, org.chromium.mojo_base.mojom.Time expectedResponseTime, org.chromium.mojo_base.mojom.BigBuffer data, org.chromium.url.internal.mojom.Origin cacheStorageOrigin, String cacheStorageCacheName);


}
