// PolicyContainerHost.java is auto generated by mojom_bindings_generator.py, do not edit


// Copyright 2014 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// This file is autogenerated by:
//     mojo/public/tools/bindings/mojom_bindings_generator.py
// For:
//     third_party/blink/public/mojom/frame/policy_container.mojom
//

package org.chromium.blink.mojom;


public interface PolicyContainerHost extends org.chromium.mojo.bindings.Interface {



    public interface Proxy extends PolicyContainerHost, org.chromium.mojo.bindings.Interface.Proxy {
    }

    Manager<PolicyContainerHost, PolicyContainerHost.Proxy> MANAGER = PolicyContainerHost_Internal.MANAGER;


    void setReferrerPolicy(
int referrerPolicy);



    void issueKeepAliveHandle(
org.chromium.mojo.bindings.InterfaceRequest<PolicyContainerHostKeepAliveHandle> receiver);


}
