// Generated by Dagger (https://dagger.dev).
package org.chromium.chrome.browser.dependency_injection;

import dagger.internal.Factory;
import dagger.internal.Preconditions;
import org.chromium.chrome.browser.lifecycle.ActivityLifecycleDispatcher;

@SuppressWarnings({
    "unchecked",
    "rawtypes"
})
public final class ChromeActivityCommonsModule_ProvideLifecycleDispatcherFactory implements Factory<ActivityLifecycleDispatcher> {
  private final ChromeActivityCommonsModule module;

  public ChromeActivityCommonsModule_ProvideLifecycleDispatcherFactory(
      ChromeActivityCommonsModule module) {
    this.module = module;
  }

  @Override
  public ActivityLifecycleDispatcher get() {
    return provideLifecycleDispatcher(module);
  }

  public static ChromeActivityCommonsModule_ProvideLifecycleDispatcherFactory create(
      ChromeActivityCommonsModule module) {
    return new ChromeActivityCommonsModule_ProvideLifecycleDispatcherFactory(module);
  }

  public static ActivityLifecycleDispatcher provideLifecycleDispatcher(
      ChromeActivityCommonsModule instance) {
    return Preconditions.checkNotNull(instance.provideLifecycleDispatcher(), "Cannot return null from a non-@Nullable @Provides method");
  }
}
