
// Copyright 2021 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// This file is autogenerated by
//     java_cpp_enum.py
// From
//     ../../chrome/browser/android/context_menu/context_menu_native_delegate_impl.h

package org.chromium.chrome.browser.contextmenu;

import androidx.annotation.IntDef;

import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;

@IntDef({
    ContextMenuImageFormat.JPEG, ContextMenuImageFormat.PNG, ContextMenuImageFormat.ORIGINAL
})
@Retention(RetentionPolicy.SOURCE)
public @interface ContextMenuImageFormat {
  int JPEG = 0;
  int PNG = 1;
  int ORIGINAL = 2;
}
