
// Copyright 2021 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// This file is autogenerated by
//     java_cpp_enum.py
// From
//     ../../chrome/browser/android/explore_sites/explore_sites_feature.h

package org.chromium.chrome.browser.explore_sites;

import androidx.annotation.IntDef;

import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;

@IntDef({
    DenseVariation.ORIGINAL, DenseVariation.DENSE_TITLE_BOTTOM, DenseVariation.DENSE_TITLE_RIGHT
})
@Retention(RetentionPolicy.SOURCE)
public @interface DenseVariation {
  int ORIGINAL = 0;
  int DENSE_TITLE_BOTTOM = 1;
  int DENSE_TITLE_RIGHT = 2;
}
