// OverlayPosition.java is auto generated by mojom_bindings_generator.py, do not edit


// Copyright 2014 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// This file is autogenerated by:
//     mojo/public/tools/bindings/mojom_bindings_generator.py
// For:
//     components/contextual_search/content/common/mojom/contextual_search_js_api_service.mojom
//

package org.chromium.contextual_search.mojom;

public final class OverlayPosition {
    private static final boolean IS_EXTENSIBLE = false;

    public static final int CLOSE = 0;
    public static final int PEEK = 1;
    public static final int EXPAND = 2;
    public static final int MAXIMIZE = 3;
    public static final int MIN_VALUE = 0;
    public static final int MAX_VALUE = 3;

    public static boolean isKnownValue(int value) {
        return value >= 0 && value <= 3;
    }

    public static void validate(int value) {
        if (IS_EXTENSIBLE || isKnownValue(value)) return;
        throw new org.chromium.mojo.bindings.DeserializationException("Invalid enum value.");
    }

    private OverlayPosition() {}
}