// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: generic_ui.proto

package org.chromium.chrome.browser.autofill_assistant.proto;

/**
 * <pre>
 * UI Actions to invoke.
 * </pre>
 *
 * Protobuf type {@code autofill_assistant.CallbackProto}
 */
public  final class CallbackProto extends
    com.google.protobuf.GeneratedMessageLite<
        CallbackProto, CallbackProto.Builder> implements
    // @@protoc_insertion_point(message_implements:autofill_assistant.CallbackProto)
    CallbackProtoOrBuilder {
  private CallbackProto() {
    conditionModelIdentifier_ = "";
  }
  private int bitField0_;
  private int kindCase_ = 0;
  private java.lang.Object kind_;
  public enum KindCase {
    SET_VALUE(1),
    SHOW_INFO_POPUP(2),
    SHOW_LIST_POPUP(3),
    COMPUTE_VALUE(4),
    SET_USER_ACTIONS(5),
    END_ACTION(6),
    SHOW_CALENDAR_POPUP(7),
    SET_TEXT(8),
    TOGGLE_USER_ACTION(9),
    SET_VIEW_VISIBILITY(11),
    SET_VIEW_ENABLED(12),
    SHOW_GENERIC_POPUP(13),
    CREATE_NESTED_UI(14),
    CLEAR_VIEW_CONTAINER(15),
    FOR_EACH(16),
    KIND_NOT_SET(0);
    private final int value;
    private KindCase(int value) {
      this.value = value;
    }
    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static KindCase valueOf(int value) {
      return forNumber(value);
    }

    public static KindCase forNumber(int value) {
      switch (value) {
        case 1: return SET_VALUE;
        case 2: return SHOW_INFO_POPUP;
        case 3: return SHOW_LIST_POPUP;
        case 4: return COMPUTE_VALUE;
        case 5: return SET_USER_ACTIONS;
        case 6: return END_ACTION;
        case 7: return SHOW_CALENDAR_POPUP;
        case 8: return SET_TEXT;
        case 9: return TOGGLE_USER_ACTION;
        case 11: return SET_VIEW_VISIBILITY;
        case 12: return SET_VIEW_ENABLED;
        case 13: return SHOW_GENERIC_POPUP;
        case 14: return CREATE_NESTED_UI;
        case 15: return CLEAR_VIEW_CONTAINER;
        case 16: return FOR_EACH;
        case 0: return KIND_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  @java.lang.Override
  public KindCase
  getKindCase() {
    return KindCase.forNumber(
        kindCase_);
  }

  private void clearKind() {
    kindCase_ = 0;
    kind_ = null;
  }

  public static final int SET_VALUE_FIELD_NUMBER = 1;
  /**
   * <code>.autofill_assistant.SetModelValueProto set_value = 1;</code>
   */
  @java.lang.Override
  public boolean hasSetValue() {
    return kindCase_ == 1;
  }
  /**
   * <code>.autofill_assistant.SetModelValueProto set_value = 1;</code>
   */
  @java.lang.Override
  public org.chromium.chrome.browser.autofill_assistant.proto.SetModelValueProto getSetValue() {
    if (kindCase_ == 1) {
       return (org.chromium.chrome.browser.autofill_assistant.proto.SetModelValueProto) kind_;
    }
    return org.chromium.chrome.browser.autofill_assistant.proto.SetModelValueProto.getDefaultInstance();
  }
  /**
   * <code>.autofill_assistant.SetModelValueProto set_value = 1;</code>
   */
  private void setSetValue(org.chromium.chrome.browser.autofill_assistant.proto.SetModelValueProto value) {
    value.getClass();
  kind_ = value;
    kindCase_ = 1;
  }
  /**
   * <code>.autofill_assistant.SetModelValueProto set_value = 1;</code>
   */
  private void mergeSetValue(org.chromium.chrome.browser.autofill_assistant.proto.SetModelValueProto value) {
    value.getClass();
  if (kindCase_ == 1 &&
        kind_ != org.chromium.chrome.browser.autofill_assistant.proto.SetModelValueProto.getDefaultInstance()) {
      kind_ = org.chromium.chrome.browser.autofill_assistant.proto.SetModelValueProto.newBuilder((org.chromium.chrome.browser.autofill_assistant.proto.SetModelValueProto) kind_)
          .mergeFrom(value).buildPartial();
    } else {
      kind_ = value;
    }
    kindCase_ = 1;
  }
  /**
   * <code>.autofill_assistant.SetModelValueProto set_value = 1;</code>
   */
  private void clearSetValue() {
    if (kindCase_ == 1) {
      kindCase_ = 0;
      kind_ = null;
    }
  }

  public static final int SHOW_INFO_POPUP_FIELD_NUMBER = 2;
  /**
   * <code>.autofill_assistant.ShowInfoPopupProto show_info_popup = 2;</code>
   */
  @java.lang.Override
  public boolean hasShowInfoPopup() {
    return kindCase_ == 2;
  }
  /**
   * <code>.autofill_assistant.ShowInfoPopupProto show_info_popup = 2;</code>
   */
  @java.lang.Override
  public org.chromium.chrome.browser.autofill_assistant.proto.ShowInfoPopupProto getShowInfoPopup() {
    if (kindCase_ == 2) {
       return (org.chromium.chrome.browser.autofill_assistant.proto.ShowInfoPopupProto) kind_;
    }
    return org.chromium.chrome.browser.autofill_assistant.proto.ShowInfoPopupProto.getDefaultInstance();
  }
  /**
   * <code>.autofill_assistant.ShowInfoPopupProto show_info_popup = 2;</code>
   */
  private void setShowInfoPopup(org.chromium.chrome.browser.autofill_assistant.proto.ShowInfoPopupProto value) {
    value.getClass();
  kind_ = value;
    kindCase_ = 2;
  }
  /**
   * <code>.autofill_assistant.ShowInfoPopupProto show_info_popup = 2;</code>
   */
  private void mergeShowInfoPopup(org.chromium.chrome.browser.autofill_assistant.proto.ShowInfoPopupProto value) {
    value.getClass();
  if (kindCase_ == 2 &&
        kind_ != org.chromium.chrome.browser.autofill_assistant.proto.ShowInfoPopupProto.getDefaultInstance()) {
      kind_ = org.chromium.chrome.browser.autofill_assistant.proto.ShowInfoPopupProto.newBuilder((org.chromium.chrome.browser.autofill_assistant.proto.ShowInfoPopupProto) kind_)
          .mergeFrom(value).buildPartial();
    } else {
      kind_ = value;
    }
    kindCase_ = 2;
  }
  /**
   * <code>.autofill_assistant.ShowInfoPopupProto show_info_popup = 2;</code>
   */
  private void clearShowInfoPopup() {
    if (kindCase_ == 2) {
      kindCase_ = 0;
      kind_ = null;
    }
  }

  public static final int SHOW_LIST_POPUP_FIELD_NUMBER = 3;
  /**
   * <code>.autofill_assistant.ShowListPopupProto show_list_popup = 3;</code>
   */
  @java.lang.Override
  public boolean hasShowListPopup() {
    return kindCase_ == 3;
  }
  /**
   * <code>.autofill_assistant.ShowListPopupProto show_list_popup = 3;</code>
   */
  @java.lang.Override
  public org.chromium.chrome.browser.autofill_assistant.proto.ShowListPopupProto getShowListPopup() {
    if (kindCase_ == 3) {
       return (org.chromium.chrome.browser.autofill_assistant.proto.ShowListPopupProto) kind_;
    }
    return org.chromium.chrome.browser.autofill_assistant.proto.ShowListPopupProto.getDefaultInstance();
  }
  /**
   * <code>.autofill_assistant.ShowListPopupProto show_list_popup = 3;</code>
   */
  private void setShowListPopup(org.chromium.chrome.browser.autofill_assistant.proto.ShowListPopupProto value) {
    value.getClass();
  kind_ = value;
    kindCase_ = 3;
  }
  /**
   * <code>.autofill_assistant.ShowListPopupProto show_list_popup = 3;</code>
   */
  private void mergeShowListPopup(org.chromium.chrome.browser.autofill_assistant.proto.ShowListPopupProto value) {
    value.getClass();
  if (kindCase_ == 3 &&
        kind_ != org.chromium.chrome.browser.autofill_assistant.proto.ShowListPopupProto.getDefaultInstance()) {
      kind_ = org.chromium.chrome.browser.autofill_assistant.proto.ShowListPopupProto.newBuilder((org.chromium.chrome.browser.autofill_assistant.proto.ShowListPopupProto) kind_)
          .mergeFrom(value).buildPartial();
    } else {
      kind_ = value;
    }
    kindCase_ = 3;
  }
  /**
   * <code>.autofill_assistant.ShowListPopupProto show_list_popup = 3;</code>
   */
  private void clearShowListPopup() {
    if (kindCase_ == 3) {
      kindCase_ = 0;
      kind_ = null;
    }
  }

  public static final int COMPUTE_VALUE_FIELD_NUMBER = 4;
  /**
   * <code>.autofill_assistant.ComputeValueProto compute_value = 4;</code>
   */
  @java.lang.Override
  public boolean hasComputeValue() {
    return kindCase_ == 4;
  }
  /**
   * <code>.autofill_assistant.ComputeValueProto compute_value = 4;</code>
   */
  @java.lang.Override
  public org.chromium.chrome.browser.autofill_assistant.proto.ComputeValueProto getComputeValue() {
    if (kindCase_ == 4) {
       return (org.chromium.chrome.browser.autofill_assistant.proto.ComputeValueProto) kind_;
    }
    return org.chromium.chrome.browser.autofill_assistant.proto.ComputeValueProto.getDefaultInstance();
  }
  /**
   * <code>.autofill_assistant.ComputeValueProto compute_value = 4;</code>
   */
  private void setComputeValue(org.chromium.chrome.browser.autofill_assistant.proto.ComputeValueProto value) {
    value.getClass();
  kind_ = value;
    kindCase_ = 4;
  }
  /**
   * <code>.autofill_assistant.ComputeValueProto compute_value = 4;</code>
   */
  private void mergeComputeValue(org.chromium.chrome.browser.autofill_assistant.proto.ComputeValueProto value) {
    value.getClass();
  if (kindCase_ == 4 &&
        kind_ != org.chromium.chrome.browser.autofill_assistant.proto.ComputeValueProto.getDefaultInstance()) {
      kind_ = org.chromium.chrome.browser.autofill_assistant.proto.ComputeValueProto.newBuilder((org.chromium.chrome.browser.autofill_assistant.proto.ComputeValueProto) kind_)
          .mergeFrom(value).buildPartial();
    } else {
      kind_ = value;
    }
    kindCase_ = 4;
  }
  /**
   * <code>.autofill_assistant.ComputeValueProto compute_value = 4;</code>
   */
  private void clearComputeValue() {
    if (kindCase_ == 4) {
      kindCase_ = 0;
      kind_ = null;
    }
  }

  public static final int SET_USER_ACTIONS_FIELD_NUMBER = 5;
  /**
   * <code>.autofill_assistant.SetUserActionsProto set_user_actions = 5;</code>
   */
  @java.lang.Override
  public boolean hasSetUserActions() {
    return kindCase_ == 5;
  }
  /**
   * <code>.autofill_assistant.SetUserActionsProto set_user_actions = 5;</code>
   */
  @java.lang.Override
  public org.chromium.chrome.browser.autofill_assistant.proto.SetUserActionsProto getSetUserActions() {
    if (kindCase_ == 5) {
       return (org.chromium.chrome.browser.autofill_assistant.proto.SetUserActionsProto) kind_;
    }
    return org.chromium.chrome.browser.autofill_assistant.proto.SetUserActionsProto.getDefaultInstance();
  }
  /**
   * <code>.autofill_assistant.SetUserActionsProto set_user_actions = 5;</code>
   */
  private void setSetUserActions(org.chromium.chrome.browser.autofill_assistant.proto.SetUserActionsProto value) {
    value.getClass();
  kind_ = value;
    kindCase_ = 5;
  }
  /**
   * <code>.autofill_assistant.SetUserActionsProto set_user_actions = 5;</code>
   */
  private void mergeSetUserActions(org.chromium.chrome.browser.autofill_assistant.proto.SetUserActionsProto value) {
    value.getClass();
  if (kindCase_ == 5 &&
        kind_ != org.chromium.chrome.browser.autofill_assistant.proto.SetUserActionsProto.getDefaultInstance()) {
      kind_ = org.chromium.chrome.browser.autofill_assistant.proto.SetUserActionsProto.newBuilder((org.chromium.chrome.browser.autofill_assistant.proto.SetUserActionsProto) kind_)
          .mergeFrom(value).buildPartial();
    } else {
      kind_ = value;
    }
    kindCase_ = 5;
  }
  /**
   * <code>.autofill_assistant.SetUserActionsProto set_user_actions = 5;</code>
   */
  private void clearSetUserActions() {
    if (kindCase_ == 5) {
      kindCase_ = 0;
      kind_ = null;
    }
  }

  public static final int END_ACTION_FIELD_NUMBER = 6;
  /**
   * <code>.autofill_assistant.EndActionProto end_action = 6;</code>
   */
  @java.lang.Override
  public boolean hasEndAction() {
    return kindCase_ == 6;
  }
  /**
   * <code>.autofill_assistant.EndActionProto end_action = 6;</code>
   */
  @java.lang.Override
  public org.chromium.chrome.browser.autofill_assistant.proto.EndActionProto getEndAction() {
    if (kindCase_ == 6) {
       return (org.chromium.chrome.browser.autofill_assistant.proto.EndActionProto) kind_;
    }
    return org.chromium.chrome.browser.autofill_assistant.proto.EndActionProto.getDefaultInstance();
  }
  /**
   * <code>.autofill_assistant.EndActionProto end_action = 6;</code>
   */
  private void setEndAction(org.chromium.chrome.browser.autofill_assistant.proto.EndActionProto value) {
    value.getClass();
  kind_ = value;
    kindCase_ = 6;
  }
  /**
   * <code>.autofill_assistant.EndActionProto end_action = 6;</code>
   */
  private void mergeEndAction(org.chromium.chrome.browser.autofill_assistant.proto.EndActionProto value) {
    value.getClass();
  if (kindCase_ == 6 &&
        kind_ != org.chromium.chrome.browser.autofill_assistant.proto.EndActionProto.getDefaultInstance()) {
      kind_ = org.chromium.chrome.browser.autofill_assistant.proto.EndActionProto.newBuilder((org.chromium.chrome.browser.autofill_assistant.proto.EndActionProto) kind_)
          .mergeFrom(value).buildPartial();
    } else {
      kind_ = value;
    }
    kindCase_ = 6;
  }
  /**
   * <code>.autofill_assistant.EndActionProto end_action = 6;</code>
   */
  private void clearEndAction() {
    if (kindCase_ == 6) {
      kindCase_ = 0;
      kind_ = null;
    }
  }

  public static final int SHOW_CALENDAR_POPUP_FIELD_NUMBER = 7;
  /**
   * <code>.autofill_assistant.ShowCalendarPopupProto show_calendar_popup = 7;</code>
   */
  @java.lang.Override
  public boolean hasShowCalendarPopup() {
    return kindCase_ == 7;
  }
  /**
   * <code>.autofill_assistant.ShowCalendarPopupProto show_calendar_popup = 7;</code>
   */
  @java.lang.Override
  public org.chromium.chrome.browser.autofill_assistant.proto.ShowCalendarPopupProto getShowCalendarPopup() {
    if (kindCase_ == 7) {
       return (org.chromium.chrome.browser.autofill_assistant.proto.ShowCalendarPopupProto) kind_;
    }
    return org.chromium.chrome.browser.autofill_assistant.proto.ShowCalendarPopupProto.getDefaultInstance();
  }
  /**
   * <code>.autofill_assistant.ShowCalendarPopupProto show_calendar_popup = 7;</code>
   */
  private void setShowCalendarPopup(org.chromium.chrome.browser.autofill_assistant.proto.ShowCalendarPopupProto value) {
    value.getClass();
  kind_ = value;
    kindCase_ = 7;
  }
  /**
   * <code>.autofill_assistant.ShowCalendarPopupProto show_calendar_popup = 7;</code>
   */
  private void mergeShowCalendarPopup(org.chromium.chrome.browser.autofill_assistant.proto.ShowCalendarPopupProto value) {
    value.getClass();
  if (kindCase_ == 7 &&
        kind_ != org.chromium.chrome.browser.autofill_assistant.proto.ShowCalendarPopupProto.getDefaultInstance()) {
      kind_ = org.chromium.chrome.browser.autofill_assistant.proto.ShowCalendarPopupProto.newBuilder((org.chromium.chrome.browser.autofill_assistant.proto.ShowCalendarPopupProto) kind_)
          .mergeFrom(value).buildPartial();
    } else {
      kind_ = value;
    }
    kindCase_ = 7;
  }
  /**
   * <code>.autofill_assistant.ShowCalendarPopupProto show_calendar_popup = 7;</code>
   */
  private void clearShowCalendarPopup() {
    if (kindCase_ == 7) {
      kindCase_ = 0;
      kind_ = null;
    }
  }

  public static final int SET_TEXT_FIELD_NUMBER = 8;
  /**
   * <code>.autofill_assistant.SetTextProto set_text = 8;</code>
   */
  @java.lang.Override
  public boolean hasSetText() {
    return kindCase_ == 8;
  }
  /**
   * <code>.autofill_assistant.SetTextProto set_text = 8;</code>
   */
  @java.lang.Override
  public org.chromium.chrome.browser.autofill_assistant.proto.SetTextProto getSetText() {
    if (kindCase_ == 8) {
       return (org.chromium.chrome.browser.autofill_assistant.proto.SetTextProto) kind_;
    }
    return org.chromium.chrome.browser.autofill_assistant.proto.SetTextProto.getDefaultInstance();
  }
  /**
   * <code>.autofill_assistant.SetTextProto set_text = 8;</code>
   */
  private void setSetText(org.chromium.chrome.browser.autofill_assistant.proto.SetTextProto value) {
    value.getClass();
  kind_ = value;
    kindCase_ = 8;
  }
  /**
   * <code>.autofill_assistant.SetTextProto set_text = 8;</code>
   */
  private void mergeSetText(org.chromium.chrome.browser.autofill_assistant.proto.SetTextProto value) {
    value.getClass();
  if (kindCase_ == 8 &&
        kind_ != org.chromium.chrome.browser.autofill_assistant.proto.SetTextProto.getDefaultInstance()) {
      kind_ = org.chromium.chrome.browser.autofill_assistant.proto.SetTextProto.newBuilder((org.chromium.chrome.browser.autofill_assistant.proto.SetTextProto) kind_)
          .mergeFrom(value).buildPartial();
    } else {
      kind_ = value;
    }
    kindCase_ = 8;
  }
  /**
   * <code>.autofill_assistant.SetTextProto set_text = 8;</code>
   */
  private void clearSetText() {
    if (kindCase_ == 8) {
      kindCase_ = 0;
      kind_ = null;
    }
  }

  public static final int TOGGLE_USER_ACTION_FIELD_NUMBER = 9;
  /**
   * <code>.autofill_assistant.ToggleUserActionProto toggle_user_action = 9;</code>
   */
  @java.lang.Override
  public boolean hasToggleUserAction() {
    return kindCase_ == 9;
  }
  /**
   * <code>.autofill_assistant.ToggleUserActionProto toggle_user_action = 9;</code>
   */
  @java.lang.Override
  public org.chromium.chrome.browser.autofill_assistant.proto.ToggleUserActionProto getToggleUserAction() {
    if (kindCase_ == 9) {
       return (org.chromium.chrome.browser.autofill_assistant.proto.ToggleUserActionProto) kind_;
    }
    return org.chromium.chrome.browser.autofill_assistant.proto.ToggleUserActionProto.getDefaultInstance();
  }
  /**
   * <code>.autofill_assistant.ToggleUserActionProto toggle_user_action = 9;</code>
   */
  private void setToggleUserAction(org.chromium.chrome.browser.autofill_assistant.proto.ToggleUserActionProto value) {
    value.getClass();
  kind_ = value;
    kindCase_ = 9;
  }
  /**
   * <code>.autofill_assistant.ToggleUserActionProto toggle_user_action = 9;</code>
   */
  private void mergeToggleUserAction(org.chromium.chrome.browser.autofill_assistant.proto.ToggleUserActionProto value) {
    value.getClass();
  if (kindCase_ == 9 &&
        kind_ != org.chromium.chrome.browser.autofill_assistant.proto.ToggleUserActionProto.getDefaultInstance()) {
      kind_ = org.chromium.chrome.browser.autofill_assistant.proto.ToggleUserActionProto.newBuilder((org.chromium.chrome.browser.autofill_assistant.proto.ToggleUserActionProto) kind_)
          .mergeFrom(value).buildPartial();
    } else {
      kind_ = value;
    }
    kindCase_ = 9;
  }
  /**
   * <code>.autofill_assistant.ToggleUserActionProto toggle_user_action = 9;</code>
   */
  private void clearToggleUserAction() {
    if (kindCase_ == 9) {
      kindCase_ = 0;
      kind_ = null;
    }
  }

  public static final int SET_VIEW_VISIBILITY_FIELD_NUMBER = 11;
  /**
   * <code>.autofill_assistant.SetViewVisibilityProto set_view_visibility = 11;</code>
   */
  @java.lang.Override
  public boolean hasSetViewVisibility() {
    return kindCase_ == 11;
  }
  /**
   * <code>.autofill_assistant.SetViewVisibilityProto set_view_visibility = 11;</code>
   */
  @java.lang.Override
  public org.chromium.chrome.browser.autofill_assistant.proto.SetViewVisibilityProto getSetViewVisibility() {
    if (kindCase_ == 11) {
       return (org.chromium.chrome.browser.autofill_assistant.proto.SetViewVisibilityProto) kind_;
    }
    return org.chromium.chrome.browser.autofill_assistant.proto.SetViewVisibilityProto.getDefaultInstance();
  }
  /**
   * <code>.autofill_assistant.SetViewVisibilityProto set_view_visibility = 11;</code>
   */
  private void setSetViewVisibility(org.chromium.chrome.browser.autofill_assistant.proto.SetViewVisibilityProto value) {
    value.getClass();
  kind_ = value;
    kindCase_ = 11;
  }
  /**
   * <code>.autofill_assistant.SetViewVisibilityProto set_view_visibility = 11;</code>
   */
  private void mergeSetViewVisibility(org.chromium.chrome.browser.autofill_assistant.proto.SetViewVisibilityProto value) {
    value.getClass();
  if (kindCase_ == 11 &&
        kind_ != org.chromium.chrome.browser.autofill_assistant.proto.SetViewVisibilityProto.getDefaultInstance()) {
      kind_ = org.chromium.chrome.browser.autofill_assistant.proto.SetViewVisibilityProto.newBuilder((org.chromium.chrome.browser.autofill_assistant.proto.SetViewVisibilityProto) kind_)
          .mergeFrom(value).buildPartial();
    } else {
      kind_ = value;
    }
    kindCase_ = 11;
  }
  /**
   * <code>.autofill_assistant.SetViewVisibilityProto set_view_visibility = 11;</code>
   */
  private void clearSetViewVisibility() {
    if (kindCase_ == 11) {
      kindCase_ = 0;
      kind_ = null;
    }
  }

  public static final int SET_VIEW_ENABLED_FIELD_NUMBER = 12;
  /**
   * <code>.autofill_assistant.SetViewEnabledProto set_view_enabled = 12;</code>
   */
  @java.lang.Override
  public boolean hasSetViewEnabled() {
    return kindCase_ == 12;
  }
  /**
   * <code>.autofill_assistant.SetViewEnabledProto set_view_enabled = 12;</code>
   */
  @java.lang.Override
  public org.chromium.chrome.browser.autofill_assistant.proto.SetViewEnabledProto getSetViewEnabled() {
    if (kindCase_ == 12) {
       return (org.chromium.chrome.browser.autofill_assistant.proto.SetViewEnabledProto) kind_;
    }
    return org.chromium.chrome.browser.autofill_assistant.proto.SetViewEnabledProto.getDefaultInstance();
  }
  /**
   * <code>.autofill_assistant.SetViewEnabledProto set_view_enabled = 12;</code>
   */
  private void setSetViewEnabled(org.chromium.chrome.browser.autofill_assistant.proto.SetViewEnabledProto value) {
    value.getClass();
  kind_ = value;
    kindCase_ = 12;
  }
  /**
   * <code>.autofill_assistant.SetViewEnabledProto set_view_enabled = 12;</code>
   */
  private void mergeSetViewEnabled(org.chromium.chrome.browser.autofill_assistant.proto.SetViewEnabledProto value) {
    value.getClass();
  if (kindCase_ == 12 &&
        kind_ != org.chromium.chrome.browser.autofill_assistant.proto.SetViewEnabledProto.getDefaultInstance()) {
      kind_ = org.chromium.chrome.browser.autofill_assistant.proto.SetViewEnabledProto.newBuilder((org.chromium.chrome.browser.autofill_assistant.proto.SetViewEnabledProto) kind_)
          .mergeFrom(value).buildPartial();
    } else {
      kind_ = value;
    }
    kindCase_ = 12;
  }
  /**
   * <code>.autofill_assistant.SetViewEnabledProto set_view_enabled = 12;</code>
   */
  private void clearSetViewEnabled() {
    if (kindCase_ == 12) {
      kindCase_ = 0;
      kind_ = null;
    }
  }

  public static final int SHOW_GENERIC_POPUP_FIELD_NUMBER = 13;
  /**
   * <code>.autofill_assistant.ShowGenericUiPopupProto show_generic_popup = 13;</code>
   */
  @java.lang.Override
  public boolean hasShowGenericPopup() {
    return kindCase_ == 13;
  }
  /**
   * <code>.autofill_assistant.ShowGenericUiPopupProto show_generic_popup = 13;</code>
   */
  @java.lang.Override
  public org.chromium.chrome.browser.autofill_assistant.proto.ShowGenericUiPopupProto getShowGenericPopup() {
    if (kindCase_ == 13) {
       return (org.chromium.chrome.browser.autofill_assistant.proto.ShowGenericUiPopupProto) kind_;
    }
    return org.chromium.chrome.browser.autofill_assistant.proto.ShowGenericUiPopupProto.getDefaultInstance();
  }
  /**
   * <code>.autofill_assistant.ShowGenericUiPopupProto show_generic_popup = 13;</code>
   */
  private void setShowGenericPopup(org.chromium.chrome.browser.autofill_assistant.proto.ShowGenericUiPopupProto value) {
    value.getClass();
  kind_ = value;
    kindCase_ = 13;
  }
  /**
   * <code>.autofill_assistant.ShowGenericUiPopupProto show_generic_popup = 13;</code>
   */
  private void mergeShowGenericPopup(org.chromium.chrome.browser.autofill_assistant.proto.ShowGenericUiPopupProto value) {
    value.getClass();
  if (kindCase_ == 13 &&
        kind_ != org.chromium.chrome.browser.autofill_assistant.proto.ShowGenericUiPopupProto.getDefaultInstance()) {
      kind_ = org.chromium.chrome.browser.autofill_assistant.proto.ShowGenericUiPopupProto.newBuilder((org.chromium.chrome.browser.autofill_assistant.proto.ShowGenericUiPopupProto) kind_)
          .mergeFrom(value).buildPartial();
    } else {
      kind_ = value;
    }
    kindCase_ = 13;
  }
  /**
   * <code>.autofill_assistant.ShowGenericUiPopupProto show_generic_popup = 13;</code>
   */
  private void clearShowGenericPopup() {
    if (kindCase_ == 13) {
      kindCase_ = 0;
      kind_ = null;
    }
  }

  public static final int CREATE_NESTED_UI_FIELD_NUMBER = 14;
  /**
   * <code>.autofill_assistant.CreateNestedGenericUiProto create_nested_ui = 14;</code>
   */
  @java.lang.Override
  public boolean hasCreateNestedUi() {
    return kindCase_ == 14;
  }
  /**
   * <code>.autofill_assistant.CreateNestedGenericUiProto create_nested_ui = 14;</code>
   */
  @java.lang.Override
  public org.chromium.chrome.browser.autofill_assistant.proto.CreateNestedGenericUiProto getCreateNestedUi() {
    if (kindCase_ == 14) {
       return (org.chromium.chrome.browser.autofill_assistant.proto.CreateNestedGenericUiProto) kind_;
    }
    return org.chromium.chrome.browser.autofill_assistant.proto.CreateNestedGenericUiProto.getDefaultInstance();
  }
  /**
   * <code>.autofill_assistant.CreateNestedGenericUiProto create_nested_ui = 14;</code>
   */
  private void setCreateNestedUi(org.chromium.chrome.browser.autofill_assistant.proto.CreateNestedGenericUiProto value) {
    value.getClass();
  kind_ = value;
    kindCase_ = 14;
  }
  /**
   * <code>.autofill_assistant.CreateNestedGenericUiProto create_nested_ui = 14;</code>
   */
  private void mergeCreateNestedUi(org.chromium.chrome.browser.autofill_assistant.proto.CreateNestedGenericUiProto value) {
    value.getClass();
  if (kindCase_ == 14 &&
        kind_ != org.chromium.chrome.browser.autofill_assistant.proto.CreateNestedGenericUiProto.getDefaultInstance()) {
      kind_ = org.chromium.chrome.browser.autofill_assistant.proto.CreateNestedGenericUiProto.newBuilder((org.chromium.chrome.browser.autofill_assistant.proto.CreateNestedGenericUiProto) kind_)
          .mergeFrom(value).buildPartial();
    } else {
      kind_ = value;
    }
    kindCase_ = 14;
  }
  /**
   * <code>.autofill_assistant.CreateNestedGenericUiProto create_nested_ui = 14;</code>
   */
  private void clearCreateNestedUi() {
    if (kindCase_ == 14) {
      kindCase_ = 0;
      kind_ = null;
    }
  }

  public static final int CLEAR_VIEW_CONTAINER_FIELD_NUMBER = 15;
  /**
   * <code>.autofill_assistant.ClearViewContainerProto clear_view_container = 15;</code>
   */
  @java.lang.Override
  public boolean hasClearViewContainer() {
    return kindCase_ == 15;
  }
  /**
   * <code>.autofill_assistant.ClearViewContainerProto clear_view_container = 15;</code>
   */
  @java.lang.Override
  public org.chromium.chrome.browser.autofill_assistant.proto.ClearViewContainerProto getClearViewContainer() {
    if (kindCase_ == 15) {
       return (org.chromium.chrome.browser.autofill_assistant.proto.ClearViewContainerProto) kind_;
    }
    return org.chromium.chrome.browser.autofill_assistant.proto.ClearViewContainerProto.getDefaultInstance();
  }
  /**
   * <code>.autofill_assistant.ClearViewContainerProto clear_view_container = 15;</code>
   */
  private void setClearViewContainer(org.chromium.chrome.browser.autofill_assistant.proto.ClearViewContainerProto value) {
    value.getClass();
  kind_ = value;
    kindCase_ = 15;
  }
  /**
   * <code>.autofill_assistant.ClearViewContainerProto clear_view_container = 15;</code>
   */
  private void mergeClearViewContainer(org.chromium.chrome.browser.autofill_assistant.proto.ClearViewContainerProto value) {
    value.getClass();
  if (kindCase_ == 15 &&
        kind_ != org.chromium.chrome.browser.autofill_assistant.proto.ClearViewContainerProto.getDefaultInstance()) {
      kind_ = org.chromium.chrome.browser.autofill_assistant.proto.ClearViewContainerProto.newBuilder((org.chromium.chrome.browser.autofill_assistant.proto.ClearViewContainerProto) kind_)
          .mergeFrom(value).buildPartial();
    } else {
      kind_ = value;
    }
    kindCase_ = 15;
  }
  /**
   * <code>.autofill_assistant.ClearViewContainerProto clear_view_container = 15;</code>
   */
  private void clearClearViewContainer() {
    if (kindCase_ == 15) {
      kindCase_ = 0;
      kind_ = null;
    }
  }

  public static final int FOR_EACH_FIELD_NUMBER = 16;
  /**
   * <code>.autofill_assistant.ForEachProto for_each = 16;</code>
   */
  @java.lang.Override
  public boolean hasForEach() {
    return kindCase_ == 16;
  }
  /**
   * <code>.autofill_assistant.ForEachProto for_each = 16;</code>
   */
  @java.lang.Override
  public org.chromium.chrome.browser.autofill_assistant.proto.ForEachProto getForEach() {
    if (kindCase_ == 16) {
       return (org.chromium.chrome.browser.autofill_assistant.proto.ForEachProto) kind_;
    }
    return org.chromium.chrome.browser.autofill_assistant.proto.ForEachProto.getDefaultInstance();
  }
  /**
   * <code>.autofill_assistant.ForEachProto for_each = 16;</code>
   */
  private void setForEach(org.chromium.chrome.browser.autofill_assistant.proto.ForEachProto value) {
    value.getClass();
  kind_ = value;
    kindCase_ = 16;
  }
  /**
   * <code>.autofill_assistant.ForEachProto for_each = 16;</code>
   */
  private void mergeForEach(org.chromium.chrome.browser.autofill_assistant.proto.ForEachProto value) {
    value.getClass();
  if (kindCase_ == 16 &&
        kind_ != org.chromium.chrome.browser.autofill_assistant.proto.ForEachProto.getDefaultInstance()) {
      kind_ = org.chromium.chrome.browser.autofill_assistant.proto.ForEachProto.newBuilder((org.chromium.chrome.browser.autofill_assistant.proto.ForEachProto) kind_)
          .mergeFrom(value).buildPartial();
    } else {
      kind_ = value;
    }
    kindCase_ = 16;
  }
  /**
   * <code>.autofill_assistant.ForEachProto for_each = 16;</code>
   */
  private void clearForEach() {
    if (kindCase_ == 16) {
      kindCase_ = 0;
      kind_ = null;
    }
  }

  public static final int CONDITION_MODEL_IDENTIFIER_FIELD_NUMBER = 10;
  private java.lang.String conditionModelIdentifier_;
  /**
   * <pre>
   * Optional model identifier pointing to a single boolean. If set, the
   * callback will only be invoked if the condition is true.
   * </pre>
   *
   * <code>optional string condition_model_identifier = 10;</code>
   * @return Whether the conditionModelIdentifier field is set.
   */
  @java.lang.Override
  public boolean hasConditionModelIdentifier() {
    return ((bitField0_ & 0x00008000) != 0);
  }
  /**
   * <pre>
   * Optional model identifier pointing to a single boolean. If set, the
   * callback will only be invoked if the condition is true.
   * </pre>
   *
   * <code>optional string condition_model_identifier = 10;</code>
   * @return The conditionModelIdentifier.
   */
  @java.lang.Override
  public java.lang.String getConditionModelIdentifier() {
    return conditionModelIdentifier_;
  }
  /**
   * <pre>
   * Optional model identifier pointing to a single boolean. If set, the
   * callback will only be invoked if the condition is true.
   * </pre>
   *
   * <code>optional string condition_model_identifier = 10;</code>
   * @return The bytes for conditionModelIdentifier.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getConditionModelIdentifierBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(conditionModelIdentifier_);
  }
  /**
   * <pre>
   * Optional model identifier pointing to a single boolean. If set, the
   * callback will only be invoked if the condition is true.
   * </pre>
   *
   * <code>optional string condition_model_identifier = 10;</code>
   * @param value The conditionModelIdentifier to set.
   */
  private void setConditionModelIdentifier(
      java.lang.String value) {
    value.getClass();
  bitField0_ |= 0x00008000;
    conditionModelIdentifier_ = value;
  }
  /**
   * <pre>
   * Optional model identifier pointing to a single boolean. If set, the
   * callback will only be invoked if the condition is true.
   * </pre>
   *
   * <code>optional string condition_model_identifier = 10;</code>
   */
  private void clearConditionModelIdentifier() {
    bitField0_ = (bitField0_ & ~0x00008000);
    conditionModelIdentifier_ = getDefaultInstance().getConditionModelIdentifier();
  }
  /**
   * <pre>
   * Optional model identifier pointing to a single boolean. If set, the
   * callback will only be invoked if the condition is true.
   * </pre>
   *
   * <code>optional string condition_model_identifier = 10;</code>
   * @param value The bytes for conditionModelIdentifier to set.
   */
  private void setConditionModelIdentifierBytes(
      com.google.protobuf.ByteString value) {
    conditionModelIdentifier_ = value.toStringUtf8();
    bitField0_ |= 0x00008000;
  }

  public static org.chromium.chrome.browser.autofill_assistant.proto.CallbackProto parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static org.chromium.chrome.browser.autofill_assistant.proto.CallbackProto parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static org.chromium.chrome.browser.autofill_assistant.proto.CallbackProto parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static org.chromium.chrome.browser.autofill_assistant.proto.CallbackProto parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static org.chromium.chrome.browser.autofill_assistant.proto.CallbackProto parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static org.chromium.chrome.browser.autofill_assistant.proto.CallbackProto parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static org.chromium.chrome.browser.autofill_assistant.proto.CallbackProto parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static org.chromium.chrome.browser.autofill_assistant.proto.CallbackProto parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static org.chromium.chrome.browser.autofill_assistant.proto.CallbackProto parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static org.chromium.chrome.browser.autofill_assistant.proto.CallbackProto parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static org.chromium.chrome.browser.autofill_assistant.proto.CallbackProto parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static org.chromium.chrome.browser.autofill_assistant.proto.CallbackProto parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(org.chromium.chrome.browser.autofill_assistant.proto.CallbackProto prototype) {
    return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * <pre>
   * UI Actions to invoke.
   * </pre>
   *
   * Protobuf type {@code autofill_assistant.CallbackProto}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        org.chromium.chrome.browser.autofill_assistant.proto.CallbackProto, Builder> implements
      // @@protoc_insertion_point(builder_implements:autofill_assistant.CallbackProto)
      org.chromium.chrome.browser.autofill_assistant.proto.CallbackProtoOrBuilder {
    // Construct using org.chromium.chrome.browser.autofill_assistant.proto.CallbackProto.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }

    @java.lang.Override
    public KindCase
        getKindCase() {
      return instance.getKindCase();
    }

    public Builder clearKind() {
      copyOnWrite();
      instance.clearKind();
      return this;
    }


    /**
     * <code>.autofill_assistant.SetModelValueProto set_value = 1;</code>
     */
    @java.lang.Override
    public boolean hasSetValue() {
      return instance.hasSetValue();
    }
    /**
     * <code>.autofill_assistant.SetModelValueProto set_value = 1;</code>
     */
    @java.lang.Override
    public org.chromium.chrome.browser.autofill_assistant.proto.SetModelValueProto getSetValue() {
      return instance.getSetValue();
    }
    /**
     * <code>.autofill_assistant.SetModelValueProto set_value = 1;</code>
     */
    public Builder setSetValue(org.chromium.chrome.browser.autofill_assistant.proto.SetModelValueProto value) {
      copyOnWrite();
      instance.setSetValue(value);
      return this;
    }
    /**
     * <code>.autofill_assistant.SetModelValueProto set_value = 1;</code>
     */
    public Builder setSetValue(
        org.chromium.chrome.browser.autofill_assistant.proto.SetModelValueProto.Builder builderForValue) {
      copyOnWrite();
      instance.setSetValue(builderForValue.build());
      return this;
    }
    /**
     * <code>.autofill_assistant.SetModelValueProto set_value = 1;</code>
     */
    public Builder mergeSetValue(org.chromium.chrome.browser.autofill_assistant.proto.SetModelValueProto value) {
      copyOnWrite();
      instance.mergeSetValue(value);
      return this;
    }
    /**
     * <code>.autofill_assistant.SetModelValueProto set_value = 1;</code>
     */
    public Builder clearSetValue() {
      copyOnWrite();
      instance.clearSetValue();
      return this;
    }

    /**
     * <code>.autofill_assistant.ShowInfoPopupProto show_info_popup = 2;</code>
     */
    @java.lang.Override
    public boolean hasShowInfoPopup() {
      return instance.hasShowInfoPopup();
    }
    /**
     * <code>.autofill_assistant.ShowInfoPopupProto show_info_popup = 2;</code>
     */
    @java.lang.Override
    public org.chromium.chrome.browser.autofill_assistant.proto.ShowInfoPopupProto getShowInfoPopup() {
      return instance.getShowInfoPopup();
    }
    /**
     * <code>.autofill_assistant.ShowInfoPopupProto show_info_popup = 2;</code>
     */
    public Builder setShowInfoPopup(org.chromium.chrome.browser.autofill_assistant.proto.ShowInfoPopupProto value) {
      copyOnWrite();
      instance.setShowInfoPopup(value);
      return this;
    }
    /**
     * <code>.autofill_assistant.ShowInfoPopupProto show_info_popup = 2;</code>
     */
    public Builder setShowInfoPopup(
        org.chromium.chrome.browser.autofill_assistant.proto.ShowInfoPopupProto.Builder builderForValue) {
      copyOnWrite();
      instance.setShowInfoPopup(builderForValue.build());
      return this;
    }
    /**
     * <code>.autofill_assistant.ShowInfoPopupProto show_info_popup = 2;</code>
     */
    public Builder mergeShowInfoPopup(org.chromium.chrome.browser.autofill_assistant.proto.ShowInfoPopupProto value) {
      copyOnWrite();
      instance.mergeShowInfoPopup(value);
      return this;
    }
    /**
     * <code>.autofill_assistant.ShowInfoPopupProto show_info_popup = 2;</code>
     */
    public Builder clearShowInfoPopup() {
      copyOnWrite();
      instance.clearShowInfoPopup();
      return this;
    }

    /**
     * <code>.autofill_assistant.ShowListPopupProto show_list_popup = 3;</code>
     */
    @java.lang.Override
    public boolean hasShowListPopup() {
      return instance.hasShowListPopup();
    }
    /**
     * <code>.autofill_assistant.ShowListPopupProto show_list_popup = 3;</code>
     */
    @java.lang.Override
    public org.chromium.chrome.browser.autofill_assistant.proto.ShowListPopupProto getShowListPopup() {
      return instance.getShowListPopup();
    }
    /**
     * <code>.autofill_assistant.ShowListPopupProto show_list_popup = 3;</code>
     */
    public Builder setShowListPopup(org.chromium.chrome.browser.autofill_assistant.proto.ShowListPopupProto value) {
      copyOnWrite();
      instance.setShowListPopup(value);
      return this;
    }
    /**
     * <code>.autofill_assistant.ShowListPopupProto show_list_popup = 3;</code>
     */
    public Builder setShowListPopup(
        org.chromium.chrome.browser.autofill_assistant.proto.ShowListPopupProto.Builder builderForValue) {
      copyOnWrite();
      instance.setShowListPopup(builderForValue.build());
      return this;
    }
    /**
     * <code>.autofill_assistant.ShowListPopupProto show_list_popup = 3;</code>
     */
    public Builder mergeShowListPopup(org.chromium.chrome.browser.autofill_assistant.proto.ShowListPopupProto value) {
      copyOnWrite();
      instance.mergeShowListPopup(value);
      return this;
    }
    /**
     * <code>.autofill_assistant.ShowListPopupProto show_list_popup = 3;</code>
     */
    public Builder clearShowListPopup() {
      copyOnWrite();
      instance.clearShowListPopup();
      return this;
    }

    /**
     * <code>.autofill_assistant.ComputeValueProto compute_value = 4;</code>
     */
    @java.lang.Override
    public boolean hasComputeValue() {
      return instance.hasComputeValue();
    }
    /**
     * <code>.autofill_assistant.ComputeValueProto compute_value = 4;</code>
     */
    @java.lang.Override
    public org.chromium.chrome.browser.autofill_assistant.proto.ComputeValueProto getComputeValue() {
      return instance.getComputeValue();
    }
    /**
     * <code>.autofill_assistant.ComputeValueProto compute_value = 4;</code>
     */
    public Builder setComputeValue(org.chromium.chrome.browser.autofill_assistant.proto.ComputeValueProto value) {
      copyOnWrite();
      instance.setComputeValue(value);
      return this;
    }
    /**
     * <code>.autofill_assistant.ComputeValueProto compute_value = 4;</code>
     */
    public Builder setComputeValue(
        org.chromium.chrome.browser.autofill_assistant.proto.ComputeValueProto.Builder builderForValue) {
      copyOnWrite();
      instance.setComputeValue(builderForValue.build());
      return this;
    }
    /**
     * <code>.autofill_assistant.ComputeValueProto compute_value = 4;</code>
     */
    public Builder mergeComputeValue(org.chromium.chrome.browser.autofill_assistant.proto.ComputeValueProto value) {
      copyOnWrite();
      instance.mergeComputeValue(value);
      return this;
    }
    /**
     * <code>.autofill_assistant.ComputeValueProto compute_value = 4;</code>
     */
    public Builder clearComputeValue() {
      copyOnWrite();
      instance.clearComputeValue();
      return this;
    }

    /**
     * <code>.autofill_assistant.SetUserActionsProto set_user_actions = 5;</code>
     */
    @java.lang.Override
    public boolean hasSetUserActions() {
      return instance.hasSetUserActions();
    }
    /**
     * <code>.autofill_assistant.SetUserActionsProto set_user_actions = 5;</code>
     */
    @java.lang.Override
    public org.chromium.chrome.browser.autofill_assistant.proto.SetUserActionsProto getSetUserActions() {
      return instance.getSetUserActions();
    }
    /**
     * <code>.autofill_assistant.SetUserActionsProto set_user_actions = 5;</code>
     */
    public Builder setSetUserActions(org.chromium.chrome.browser.autofill_assistant.proto.SetUserActionsProto value) {
      copyOnWrite();
      instance.setSetUserActions(value);
      return this;
    }
    /**
     * <code>.autofill_assistant.SetUserActionsProto set_user_actions = 5;</code>
     */
    public Builder setSetUserActions(
        org.chromium.chrome.browser.autofill_assistant.proto.SetUserActionsProto.Builder builderForValue) {
      copyOnWrite();
      instance.setSetUserActions(builderForValue.build());
      return this;
    }
    /**
     * <code>.autofill_assistant.SetUserActionsProto set_user_actions = 5;</code>
     */
    public Builder mergeSetUserActions(org.chromium.chrome.browser.autofill_assistant.proto.SetUserActionsProto value) {
      copyOnWrite();
      instance.mergeSetUserActions(value);
      return this;
    }
    /**
     * <code>.autofill_assistant.SetUserActionsProto set_user_actions = 5;</code>
     */
    public Builder clearSetUserActions() {
      copyOnWrite();
      instance.clearSetUserActions();
      return this;
    }

    /**
     * <code>.autofill_assistant.EndActionProto end_action = 6;</code>
     */
    @java.lang.Override
    public boolean hasEndAction() {
      return instance.hasEndAction();
    }
    /**
     * <code>.autofill_assistant.EndActionProto end_action = 6;</code>
     */
    @java.lang.Override
    public org.chromium.chrome.browser.autofill_assistant.proto.EndActionProto getEndAction() {
      return instance.getEndAction();
    }
    /**
     * <code>.autofill_assistant.EndActionProto end_action = 6;</code>
     */
    public Builder setEndAction(org.chromium.chrome.browser.autofill_assistant.proto.EndActionProto value) {
      copyOnWrite();
      instance.setEndAction(value);
      return this;
    }
    /**
     * <code>.autofill_assistant.EndActionProto end_action = 6;</code>
     */
    public Builder setEndAction(
        org.chromium.chrome.browser.autofill_assistant.proto.EndActionProto.Builder builderForValue) {
      copyOnWrite();
      instance.setEndAction(builderForValue.build());
      return this;
    }
    /**
     * <code>.autofill_assistant.EndActionProto end_action = 6;</code>
     */
    public Builder mergeEndAction(org.chromium.chrome.browser.autofill_assistant.proto.EndActionProto value) {
      copyOnWrite();
      instance.mergeEndAction(value);
      return this;
    }
    /**
     * <code>.autofill_assistant.EndActionProto end_action = 6;</code>
     */
    public Builder clearEndAction() {
      copyOnWrite();
      instance.clearEndAction();
      return this;
    }

    /**
     * <code>.autofill_assistant.ShowCalendarPopupProto show_calendar_popup = 7;</code>
     */
    @java.lang.Override
    public boolean hasShowCalendarPopup() {
      return instance.hasShowCalendarPopup();
    }
    /**
     * <code>.autofill_assistant.ShowCalendarPopupProto show_calendar_popup = 7;</code>
     */
    @java.lang.Override
    public org.chromium.chrome.browser.autofill_assistant.proto.ShowCalendarPopupProto getShowCalendarPopup() {
      return instance.getShowCalendarPopup();
    }
    /**
     * <code>.autofill_assistant.ShowCalendarPopupProto show_calendar_popup = 7;</code>
     */
    public Builder setShowCalendarPopup(org.chromium.chrome.browser.autofill_assistant.proto.ShowCalendarPopupProto value) {
      copyOnWrite();
      instance.setShowCalendarPopup(value);
      return this;
    }
    /**
     * <code>.autofill_assistant.ShowCalendarPopupProto show_calendar_popup = 7;</code>
     */
    public Builder setShowCalendarPopup(
        org.chromium.chrome.browser.autofill_assistant.proto.ShowCalendarPopupProto.Builder builderForValue) {
      copyOnWrite();
      instance.setShowCalendarPopup(builderForValue.build());
      return this;
    }
    /**
     * <code>.autofill_assistant.ShowCalendarPopupProto show_calendar_popup = 7;</code>
     */
    public Builder mergeShowCalendarPopup(org.chromium.chrome.browser.autofill_assistant.proto.ShowCalendarPopupProto value) {
      copyOnWrite();
      instance.mergeShowCalendarPopup(value);
      return this;
    }
    /**
     * <code>.autofill_assistant.ShowCalendarPopupProto show_calendar_popup = 7;</code>
     */
    public Builder clearShowCalendarPopup() {
      copyOnWrite();
      instance.clearShowCalendarPopup();
      return this;
    }

    /**
     * <code>.autofill_assistant.SetTextProto set_text = 8;</code>
     */
    @java.lang.Override
    public boolean hasSetText() {
      return instance.hasSetText();
    }
    /**
     * <code>.autofill_assistant.SetTextProto set_text = 8;</code>
     */
    @java.lang.Override
    public org.chromium.chrome.browser.autofill_assistant.proto.SetTextProto getSetText() {
      return instance.getSetText();
    }
    /**
     * <code>.autofill_assistant.SetTextProto set_text = 8;</code>
     */
    public Builder setSetText(org.chromium.chrome.browser.autofill_assistant.proto.SetTextProto value) {
      copyOnWrite();
      instance.setSetText(value);
      return this;
    }
    /**
     * <code>.autofill_assistant.SetTextProto set_text = 8;</code>
     */
    public Builder setSetText(
        org.chromium.chrome.browser.autofill_assistant.proto.SetTextProto.Builder builderForValue) {
      copyOnWrite();
      instance.setSetText(builderForValue.build());
      return this;
    }
    /**
     * <code>.autofill_assistant.SetTextProto set_text = 8;</code>
     */
    public Builder mergeSetText(org.chromium.chrome.browser.autofill_assistant.proto.SetTextProto value) {
      copyOnWrite();
      instance.mergeSetText(value);
      return this;
    }
    /**
     * <code>.autofill_assistant.SetTextProto set_text = 8;</code>
     */
    public Builder clearSetText() {
      copyOnWrite();
      instance.clearSetText();
      return this;
    }

    /**
     * <code>.autofill_assistant.ToggleUserActionProto toggle_user_action = 9;</code>
     */
    @java.lang.Override
    public boolean hasToggleUserAction() {
      return instance.hasToggleUserAction();
    }
    /**
     * <code>.autofill_assistant.ToggleUserActionProto toggle_user_action = 9;</code>
     */
    @java.lang.Override
    public org.chromium.chrome.browser.autofill_assistant.proto.ToggleUserActionProto getToggleUserAction() {
      return instance.getToggleUserAction();
    }
    /**
     * <code>.autofill_assistant.ToggleUserActionProto toggle_user_action = 9;</code>
     */
    public Builder setToggleUserAction(org.chromium.chrome.browser.autofill_assistant.proto.ToggleUserActionProto value) {
      copyOnWrite();
      instance.setToggleUserAction(value);
      return this;
    }
    /**
     * <code>.autofill_assistant.ToggleUserActionProto toggle_user_action = 9;</code>
     */
    public Builder setToggleUserAction(
        org.chromium.chrome.browser.autofill_assistant.proto.ToggleUserActionProto.Builder builderForValue) {
      copyOnWrite();
      instance.setToggleUserAction(builderForValue.build());
      return this;
    }
    /**
     * <code>.autofill_assistant.ToggleUserActionProto toggle_user_action = 9;</code>
     */
    public Builder mergeToggleUserAction(org.chromium.chrome.browser.autofill_assistant.proto.ToggleUserActionProto value) {
      copyOnWrite();
      instance.mergeToggleUserAction(value);
      return this;
    }
    /**
     * <code>.autofill_assistant.ToggleUserActionProto toggle_user_action = 9;</code>
     */
    public Builder clearToggleUserAction() {
      copyOnWrite();
      instance.clearToggleUserAction();
      return this;
    }

    /**
     * <code>.autofill_assistant.SetViewVisibilityProto set_view_visibility = 11;</code>
     */
    @java.lang.Override
    public boolean hasSetViewVisibility() {
      return instance.hasSetViewVisibility();
    }
    /**
     * <code>.autofill_assistant.SetViewVisibilityProto set_view_visibility = 11;</code>
     */
    @java.lang.Override
    public org.chromium.chrome.browser.autofill_assistant.proto.SetViewVisibilityProto getSetViewVisibility() {
      return instance.getSetViewVisibility();
    }
    /**
     * <code>.autofill_assistant.SetViewVisibilityProto set_view_visibility = 11;</code>
     */
    public Builder setSetViewVisibility(org.chromium.chrome.browser.autofill_assistant.proto.SetViewVisibilityProto value) {
      copyOnWrite();
      instance.setSetViewVisibility(value);
      return this;
    }
    /**
     * <code>.autofill_assistant.SetViewVisibilityProto set_view_visibility = 11;</code>
     */
    public Builder setSetViewVisibility(
        org.chromium.chrome.browser.autofill_assistant.proto.SetViewVisibilityProto.Builder builderForValue) {
      copyOnWrite();
      instance.setSetViewVisibility(builderForValue.build());
      return this;
    }
    /**
     * <code>.autofill_assistant.SetViewVisibilityProto set_view_visibility = 11;</code>
     */
    public Builder mergeSetViewVisibility(org.chromium.chrome.browser.autofill_assistant.proto.SetViewVisibilityProto value) {
      copyOnWrite();
      instance.mergeSetViewVisibility(value);
      return this;
    }
    /**
     * <code>.autofill_assistant.SetViewVisibilityProto set_view_visibility = 11;</code>
     */
    public Builder clearSetViewVisibility() {
      copyOnWrite();
      instance.clearSetViewVisibility();
      return this;
    }

    /**
     * <code>.autofill_assistant.SetViewEnabledProto set_view_enabled = 12;</code>
     */
    @java.lang.Override
    public boolean hasSetViewEnabled() {
      return instance.hasSetViewEnabled();
    }
    /**
     * <code>.autofill_assistant.SetViewEnabledProto set_view_enabled = 12;</code>
     */
    @java.lang.Override
    public org.chromium.chrome.browser.autofill_assistant.proto.SetViewEnabledProto getSetViewEnabled() {
      return instance.getSetViewEnabled();
    }
    /**
     * <code>.autofill_assistant.SetViewEnabledProto set_view_enabled = 12;</code>
     */
    public Builder setSetViewEnabled(org.chromium.chrome.browser.autofill_assistant.proto.SetViewEnabledProto value) {
      copyOnWrite();
      instance.setSetViewEnabled(value);
      return this;
    }
    /**
     * <code>.autofill_assistant.SetViewEnabledProto set_view_enabled = 12;</code>
     */
    public Builder setSetViewEnabled(
        org.chromium.chrome.browser.autofill_assistant.proto.SetViewEnabledProto.Builder builderForValue) {
      copyOnWrite();
      instance.setSetViewEnabled(builderForValue.build());
      return this;
    }
    /**
     * <code>.autofill_assistant.SetViewEnabledProto set_view_enabled = 12;</code>
     */
    public Builder mergeSetViewEnabled(org.chromium.chrome.browser.autofill_assistant.proto.SetViewEnabledProto value) {
      copyOnWrite();
      instance.mergeSetViewEnabled(value);
      return this;
    }
    /**
     * <code>.autofill_assistant.SetViewEnabledProto set_view_enabled = 12;</code>
     */
    public Builder clearSetViewEnabled() {
      copyOnWrite();
      instance.clearSetViewEnabled();
      return this;
    }

    /**
     * <code>.autofill_assistant.ShowGenericUiPopupProto show_generic_popup = 13;</code>
     */
    @java.lang.Override
    public boolean hasShowGenericPopup() {
      return instance.hasShowGenericPopup();
    }
    /**
     * <code>.autofill_assistant.ShowGenericUiPopupProto show_generic_popup = 13;</code>
     */
    @java.lang.Override
    public org.chromium.chrome.browser.autofill_assistant.proto.ShowGenericUiPopupProto getShowGenericPopup() {
      return instance.getShowGenericPopup();
    }
    /**
     * <code>.autofill_assistant.ShowGenericUiPopupProto show_generic_popup = 13;</code>
     */
    public Builder setShowGenericPopup(org.chromium.chrome.browser.autofill_assistant.proto.ShowGenericUiPopupProto value) {
      copyOnWrite();
      instance.setShowGenericPopup(value);
      return this;
    }
    /**
     * <code>.autofill_assistant.ShowGenericUiPopupProto show_generic_popup = 13;</code>
     */
    public Builder setShowGenericPopup(
        org.chromium.chrome.browser.autofill_assistant.proto.ShowGenericUiPopupProto.Builder builderForValue) {
      copyOnWrite();
      instance.setShowGenericPopup(builderForValue.build());
      return this;
    }
    /**
     * <code>.autofill_assistant.ShowGenericUiPopupProto show_generic_popup = 13;</code>
     */
    public Builder mergeShowGenericPopup(org.chromium.chrome.browser.autofill_assistant.proto.ShowGenericUiPopupProto value) {
      copyOnWrite();
      instance.mergeShowGenericPopup(value);
      return this;
    }
    /**
     * <code>.autofill_assistant.ShowGenericUiPopupProto show_generic_popup = 13;</code>
     */
    public Builder clearShowGenericPopup() {
      copyOnWrite();
      instance.clearShowGenericPopup();
      return this;
    }

    /**
     * <code>.autofill_assistant.CreateNestedGenericUiProto create_nested_ui = 14;</code>
     */
    @java.lang.Override
    public boolean hasCreateNestedUi() {
      return instance.hasCreateNestedUi();
    }
    /**
     * <code>.autofill_assistant.CreateNestedGenericUiProto create_nested_ui = 14;</code>
     */
    @java.lang.Override
    public org.chromium.chrome.browser.autofill_assistant.proto.CreateNestedGenericUiProto getCreateNestedUi() {
      return instance.getCreateNestedUi();
    }
    /**
     * <code>.autofill_assistant.CreateNestedGenericUiProto create_nested_ui = 14;</code>
     */
    public Builder setCreateNestedUi(org.chromium.chrome.browser.autofill_assistant.proto.CreateNestedGenericUiProto value) {
      copyOnWrite();
      instance.setCreateNestedUi(value);
      return this;
    }
    /**
     * <code>.autofill_assistant.CreateNestedGenericUiProto create_nested_ui = 14;</code>
     */
    public Builder setCreateNestedUi(
        org.chromium.chrome.browser.autofill_assistant.proto.CreateNestedGenericUiProto.Builder builderForValue) {
      copyOnWrite();
      instance.setCreateNestedUi(builderForValue.build());
      return this;
    }
    /**
     * <code>.autofill_assistant.CreateNestedGenericUiProto create_nested_ui = 14;</code>
     */
    public Builder mergeCreateNestedUi(org.chromium.chrome.browser.autofill_assistant.proto.CreateNestedGenericUiProto value) {
      copyOnWrite();
      instance.mergeCreateNestedUi(value);
      return this;
    }
    /**
     * <code>.autofill_assistant.CreateNestedGenericUiProto create_nested_ui = 14;</code>
     */
    public Builder clearCreateNestedUi() {
      copyOnWrite();
      instance.clearCreateNestedUi();
      return this;
    }

    /**
     * <code>.autofill_assistant.ClearViewContainerProto clear_view_container = 15;</code>
     */
    @java.lang.Override
    public boolean hasClearViewContainer() {
      return instance.hasClearViewContainer();
    }
    /**
     * <code>.autofill_assistant.ClearViewContainerProto clear_view_container = 15;</code>
     */
    @java.lang.Override
    public org.chromium.chrome.browser.autofill_assistant.proto.ClearViewContainerProto getClearViewContainer() {
      return instance.getClearViewContainer();
    }
    /**
     * <code>.autofill_assistant.ClearViewContainerProto clear_view_container = 15;</code>
     */
    public Builder setClearViewContainer(org.chromium.chrome.browser.autofill_assistant.proto.ClearViewContainerProto value) {
      copyOnWrite();
      instance.setClearViewContainer(value);
      return this;
    }
    /**
     * <code>.autofill_assistant.ClearViewContainerProto clear_view_container = 15;</code>
     */
    public Builder setClearViewContainer(
        org.chromium.chrome.browser.autofill_assistant.proto.ClearViewContainerProto.Builder builderForValue) {
      copyOnWrite();
      instance.setClearViewContainer(builderForValue.build());
      return this;
    }
    /**
     * <code>.autofill_assistant.ClearViewContainerProto clear_view_container = 15;</code>
     */
    public Builder mergeClearViewContainer(org.chromium.chrome.browser.autofill_assistant.proto.ClearViewContainerProto value) {
      copyOnWrite();
      instance.mergeClearViewContainer(value);
      return this;
    }
    /**
     * <code>.autofill_assistant.ClearViewContainerProto clear_view_container = 15;</code>
     */
    public Builder clearClearViewContainer() {
      copyOnWrite();
      instance.clearClearViewContainer();
      return this;
    }

    /**
     * <code>.autofill_assistant.ForEachProto for_each = 16;</code>
     */
    @java.lang.Override
    public boolean hasForEach() {
      return instance.hasForEach();
    }
    /**
     * <code>.autofill_assistant.ForEachProto for_each = 16;</code>
     */
    @java.lang.Override
    public org.chromium.chrome.browser.autofill_assistant.proto.ForEachProto getForEach() {
      return instance.getForEach();
    }
    /**
     * <code>.autofill_assistant.ForEachProto for_each = 16;</code>
     */
    public Builder setForEach(org.chromium.chrome.browser.autofill_assistant.proto.ForEachProto value) {
      copyOnWrite();
      instance.setForEach(value);
      return this;
    }
    /**
     * <code>.autofill_assistant.ForEachProto for_each = 16;</code>
     */
    public Builder setForEach(
        org.chromium.chrome.browser.autofill_assistant.proto.ForEachProto.Builder builderForValue) {
      copyOnWrite();
      instance.setForEach(builderForValue.build());
      return this;
    }
    /**
     * <code>.autofill_assistant.ForEachProto for_each = 16;</code>
     */
    public Builder mergeForEach(org.chromium.chrome.browser.autofill_assistant.proto.ForEachProto value) {
      copyOnWrite();
      instance.mergeForEach(value);
      return this;
    }
    /**
     * <code>.autofill_assistant.ForEachProto for_each = 16;</code>
     */
    public Builder clearForEach() {
      copyOnWrite();
      instance.clearForEach();
      return this;
    }

    /**
     * <pre>
     * Optional model identifier pointing to a single boolean. If set, the
     * callback will only be invoked if the condition is true.
     * </pre>
     *
     * <code>optional string condition_model_identifier = 10;</code>
     * @return Whether the conditionModelIdentifier field is set.
     */
    @java.lang.Override
    public boolean hasConditionModelIdentifier() {
      return instance.hasConditionModelIdentifier();
    }
    /**
     * <pre>
     * Optional model identifier pointing to a single boolean. If set, the
     * callback will only be invoked if the condition is true.
     * </pre>
     *
     * <code>optional string condition_model_identifier = 10;</code>
     * @return The conditionModelIdentifier.
     */
    @java.lang.Override
    public java.lang.String getConditionModelIdentifier() {
      return instance.getConditionModelIdentifier();
    }
    /**
     * <pre>
     * Optional model identifier pointing to a single boolean. If set, the
     * callback will only be invoked if the condition is true.
     * </pre>
     *
     * <code>optional string condition_model_identifier = 10;</code>
     * @return The bytes for conditionModelIdentifier.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getConditionModelIdentifierBytes() {
      return instance.getConditionModelIdentifierBytes();
    }
    /**
     * <pre>
     * Optional model identifier pointing to a single boolean. If set, the
     * callback will only be invoked if the condition is true.
     * </pre>
     *
     * <code>optional string condition_model_identifier = 10;</code>
     * @param value The conditionModelIdentifier to set.
     * @return This builder for chaining.
     */
    public Builder setConditionModelIdentifier(
        java.lang.String value) {
      copyOnWrite();
      instance.setConditionModelIdentifier(value);
      return this;
    }
    /**
     * <pre>
     * Optional model identifier pointing to a single boolean. If set, the
     * callback will only be invoked if the condition is true.
     * </pre>
     *
     * <code>optional string condition_model_identifier = 10;</code>
     * @return This builder for chaining.
     */
    public Builder clearConditionModelIdentifier() {
      copyOnWrite();
      instance.clearConditionModelIdentifier();
      return this;
    }
    /**
     * <pre>
     * Optional model identifier pointing to a single boolean. If set, the
     * callback will only be invoked if the condition is true.
     * </pre>
     *
     * <code>optional string condition_model_identifier = 10;</code>
     * @param value The bytes for conditionModelIdentifier to set.
     * @return This builder for chaining.
     */
    public Builder setConditionModelIdentifierBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setConditionModelIdentifierBytes(value);
      return this;
    }

    // @@protoc_insertion_point(builder_scope:autofill_assistant.CallbackProto)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new org.chromium.chrome.browser.autofill_assistant.proto.CallbackProto();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "kind_",
            "kindCase_",
            "bitField0_",
            org.chromium.chrome.browser.autofill_assistant.proto.SetModelValueProto.class,
            org.chromium.chrome.browser.autofill_assistant.proto.ShowInfoPopupProto.class,
            org.chromium.chrome.browser.autofill_assistant.proto.ShowListPopupProto.class,
            org.chromium.chrome.browser.autofill_assistant.proto.ComputeValueProto.class,
            org.chromium.chrome.browser.autofill_assistant.proto.SetUserActionsProto.class,
            org.chromium.chrome.browser.autofill_assistant.proto.EndActionProto.class,
            org.chromium.chrome.browser.autofill_assistant.proto.ShowCalendarPopupProto.class,
            org.chromium.chrome.browser.autofill_assistant.proto.SetTextProto.class,
            org.chromium.chrome.browser.autofill_assistant.proto.ToggleUserActionProto.class,
            "conditionModelIdentifier_",
            org.chromium.chrome.browser.autofill_assistant.proto.SetViewVisibilityProto.class,
            org.chromium.chrome.browser.autofill_assistant.proto.SetViewEnabledProto.class,
            org.chromium.chrome.browser.autofill_assistant.proto.ShowGenericUiPopupProto.class,
            org.chromium.chrome.browser.autofill_assistant.proto.CreateNestedGenericUiProto.class,
            org.chromium.chrome.browser.autofill_assistant.proto.ClearViewContainerProto.class,
            org.chromium.chrome.browser.autofill_assistant.proto.ForEachProto.class,
          };
          java.lang.String info =
              "\u0001\u0010\u0001\u0001\u0001\u0010\u0010\u0000\u0000\u0000\u0001\u103c\u0000\u0002" +
              "\u103c\u0000\u0003\u103c\u0000\u0004\u103c\u0000\u0005\u103c\u0000\u0006\u103c\u0000" +
              "\u0007\u103c\u0000\b\u103c\u0000\t\u103c\u0000\n\u1008\u000f\u000b\u103c\u0000\f" +
              "\u103c\u0000\r\u103c\u0000\u000e\u103c\u0000\u000f\u103c\u0000\u0010\u103c\u0000" +
              "";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<org.chromium.chrome.browser.autofill_assistant.proto.CallbackProto> parser = PARSER;
        if (parser == null) {
          synchronized (org.chromium.chrome.browser.autofill_assistant.proto.CallbackProto.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<org.chromium.chrome.browser.autofill_assistant.proto.CallbackProto>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:autofill_assistant.CallbackProto)
  private static final org.chromium.chrome.browser.autofill_assistant.proto.CallbackProto DEFAULT_INSTANCE;
  static {
    CallbackProto defaultInstance = new CallbackProto();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      CallbackProto.class, defaultInstance);
  }

  public static org.chromium.chrome.browser.autofill_assistant.proto.CallbackProto getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<CallbackProto> PARSER;

  public static com.google.protobuf.Parser<CallbackProto> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

