// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service.proto

package org.chromium.chrome.browser.autofill_assistant.proto;

/**
 * Protobuf type {@code autofill_assistant.DetailsProto}
 */
public  final class DetailsProto extends
    com.google.protobuf.GeneratedMessageLite<
        DetailsProto, DetailsProto.Builder> implements
    // @@protoc_insertion_point(message_implements:autofill_assistant.DetailsProto)
    DetailsProtoOrBuilder {
  private DetailsProto() {
    title_ = "";
    imageAccessibilityHint_ = "";
    totalPriceLabel_ = "";
    totalPrice_ = "";
    descriptionLine1_ = "";
    descriptionLine2_ = "";
    descriptionLine3_ = "";
    description_ = "";
  }
  public interface ImageClickthroughDataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:autofill_assistant.DetailsProto.ImageClickthroughData)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <pre>
     * Whether to show the original URL where image is extracted from. Only
     * useful when 'image_url' is set.
     * </pre>
     *
     * <code>optional bool allow_clickthrough = 1;</code>
     * @return Whether the allowClickthrough field is set.
     */
    boolean hasAllowClickthrough();
    /**
     * <pre>
     * Whether to show the original URL where image is extracted from. Only
     * useful when 'image_url' is set.
     * </pre>
     *
     * <code>optional bool allow_clickthrough = 1;</code>
     * @return The allowClickthrough.
     */
    boolean getAllowClickthrough();

    /**
     * <pre>
     * When image clickthrough is allowed, below texts are used to customize the
     * modal dialog shown to user *if* they are set, otherwise default texts
     * will be used.
     * </pre>
     *
     * <code>optional string description = 2;</code>
     * @return Whether the description field is set.
     */
    boolean hasDescription();
    /**
     * <pre>
     * When image clickthrough is allowed, below texts are used to customize the
     * modal dialog shown to user *if* they are set, otherwise default texts
     * will be used.
     * </pre>
     *
     * <code>optional string description = 2;</code>
     * @return The description.
     */
    java.lang.String getDescription();
    /**
     * <pre>
     * When image clickthrough is allowed, below texts are used to customize the
     * modal dialog shown to user *if* they are set, otherwise default texts
     * will be used.
     * </pre>
     *
     * <code>optional string description = 2;</code>
     * @return The bytes for description.
     */
    com.google.protobuf.ByteString
        getDescriptionBytes();

    /**
     * <code>optional string positive_text = 3;</code>
     * @return Whether the positiveText field is set.
     */
    boolean hasPositiveText();
    /**
     * <code>optional string positive_text = 3;</code>
     * @return The positiveText.
     */
    java.lang.String getPositiveText();
    /**
     * <code>optional string positive_text = 3;</code>
     * @return The bytes for positiveText.
     */
    com.google.protobuf.ByteString
        getPositiveTextBytes();

    /**
     * <code>optional string negative_text = 4;</code>
     * @return Whether the negativeText field is set.
     */
    boolean hasNegativeText();
    /**
     * <code>optional string negative_text = 4;</code>
     * @return The negativeText.
     */
    java.lang.String getNegativeText();
    /**
     * <code>optional string negative_text = 4;</code>
     * @return The bytes for negativeText.
     */
    com.google.protobuf.ByteString
        getNegativeTextBytes();

    /**
     * <pre>
     * The url to present when user did choose to clickthrough.
     * </pre>
     *
     * <code>optional string clickthrough_url = 5;</code>
     * @return Whether the clickthroughUrl field is set.
     */
    boolean hasClickthroughUrl();
    /**
     * <pre>
     * The url to present when user did choose to clickthrough.
     * </pre>
     *
     * <code>optional string clickthrough_url = 5;</code>
     * @return The clickthroughUrl.
     */
    java.lang.String getClickthroughUrl();
    /**
     * <pre>
     * The url to present when user did choose to clickthrough.
     * </pre>
     *
     * <code>optional string clickthrough_url = 5;</code>
     * @return The bytes for clickthroughUrl.
     */
    com.google.protobuf.ByteString
        getClickthroughUrlBytes();
  }
  /**
   * <pre>
   * Specifies what happens when user tap on the image in the details section.
   * </pre>
   *
   * Protobuf type {@code autofill_assistant.DetailsProto.ImageClickthroughData}
   */
  public  static final class ImageClickthroughData extends
      com.google.protobuf.GeneratedMessageLite<
          ImageClickthroughData, ImageClickthroughData.Builder> implements
      // @@protoc_insertion_point(message_implements:autofill_assistant.DetailsProto.ImageClickthroughData)
      ImageClickthroughDataOrBuilder {
    private ImageClickthroughData() {
      description_ = "";
      positiveText_ = "";
      negativeText_ = "";
      clickthroughUrl_ = "";
    }
    private int bitField0_;
    public static final int ALLOW_CLICKTHROUGH_FIELD_NUMBER = 1;
    private boolean allowClickthrough_;
    /**
     * <pre>
     * Whether to show the original URL where image is extracted from. Only
     * useful when 'image_url' is set.
     * </pre>
     *
     * <code>optional bool allow_clickthrough = 1;</code>
     * @return Whether the allowClickthrough field is set.
     */
    @java.lang.Override
    public boolean hasAllowClickthrough() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     * Whether to show the original URL where image is extracted from. Only
     * useful when 'image_url' is set.
     * </pre>
     *
     * <code>optional bool allow_clickthrough = 1;</code>
     * @return The allowClickthrough.
     */
    @java.lang.Override
    public boolean getAllowClickthrough() {
      return allowClickthrough_;
    }
    /**
     * <pre>
     * Whether to show the original URL where image is extracted from. Only
     * useful when 'image_url' is set.
     * </pre>
     *
     * <code>optional bool allow_clickthrough = 1;</code>
     * @param value The allowClickthrough to set.
     */
    private void setAllowClickthrough(boolean value) {
      bitField0_ |= 0x00000001;
      allowClickthrough_ = value;
    }
    /**
     * <pre>
     * Whether to show the original URL where image is extracted from. Only
     * useful when 'image_url' is set.
     * </pre>
     *
     * <code>optional bool allow_clickthrough = 1;</code>
     */
    private void clearAllowClickthrough() {
      bitField0_ = (bitField0_ & ~0x00000001);
      allowClickthrough_ = false;
    }

    public static final int DESCRIPTION_FIELD_NUMBER = 2;
    private java.lang.String description_;
    /**
     * <pre>
     * When image clickthrough is allowed, below texts are used to customize the
     * modal dialog shown to user *if* they are set, otherwise default texts
     * will be used.
     * </pre>
     *
     * <code>optional string description = 2;</code>
     * @return Whether the description field is set.
     */
    @java.lang.Override
    public boolean hasDescription() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <pre>
     * When image clickthrough is allowed, below texts are used to customize the
     * modal dialog shown to user *if* they are set, otherwise default texts
     * will be used.
     * </pre>
     *
     * <code>optional string description = 2;</code>
     * @return The description.
     */
    @java.lang.Override
    public java.lang.String getDescription() {
      return description_;
    }
    /**
     * <pre>
     * When image clickthrough is allowed, below texts are used to customize the
     * modal dialog shown to user *if* they are set, otherwise default texts
     * will be used.
     * </pre>
     *
     * <code>optional string description = 2;</code>
     * @return The bytes for description.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getDescriptionBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(description_);
    }
    /**
     * <pre>
     * When image clickthrough is allowed, below texts are used to customize the
     * modal dialog shown to user *if* they are set, otherwise default texts
     * will be used.
     * </pre>
     *
     * <code>optional string description = 2;</code>
     * @param value The description to set.
     */
    private void setDescription(
        java.lang.String value) {
      value.getClass();
  bitField0_ |= 0x00000002;
      description_ = value;
    }
    /**
     * <pre>
     * When image clickthrough is allowed, below texts are used to customize the
     * modal dialog shown to user *if* they are set, otherwise default texts
     * will be used.
     * </pre>
     *
     * <code>optional string description = 2;</code>
     */
    private void clearDescription() {
      bitField0_ = (bitField0_ & ~0x00000002);
      description_ = getDefaultInstance().getDescription();
    }
    /**
     * <pre>
     * When image clickthrough is allowed, below texts are used to customize the
     * modal dialog shown to user *if* they are set, otherwise default texts
     * will be used.
     * </pre>
     *
     * <code>optional string description = 2;</code>
     * @param value The bytes for description to set.
     */
    private void setDescriptionBytes(
        com.google.protobuf.ByteString value) {
      description_ = value.toStringUtf8();
      bitField0_ |= 0x00000002;
    }

    public static final int POSITIVE_TEXT_FIELD_NUMBER = 3;
    private java.lang.String positiveText_;
    /**
     * <code>optional string positive_text = 3;</code>
     * @return Whether the positiveText field is set.
     */
    @java.lang.Override
    public boolean hasPositiveText() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional string positive_text = 3;</code>
     * @return The positiveText.
     */
    @java.lang.Override
    public java.lang.String getPositiveText() {
      return positiveText_;
    }
    /**
     * <code>optional string positive_text = 3;</code>
     * @return The bytes for positiveText.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getPositiveTextBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(positiveText_);
    }
    /**
     * <code>optional string positive_text = 3;</code>
     * @param value The positiveText to set.
     */
    private void setPositiveText(
        java.lang.String value) {
      value.getClass();
  bitField0_ |= 0x00000004;
      positiveText_ = value;
    }
    /**
     * <code>optional string positive_text = 3;</code>
     */
    private void clearPositiveText() {
      bitField0_ = (bitField0_ & ~0x00000004);
      positiveText_ = getDefaultInstance().getPositiveText();
    }
    /**
     * <code>optional string positive_text = 3;</code>
     * @param value The bytes for positiveText to set.
     */
    private void setPositiveTextBytes(
        com.google.protobuf.ByteString value) {
      positiveText_ = value.toStringUtf8();
      bitField0_ |= 0x00000004;
    }

    public static final int NEGATIVE_TEXT_FIELD_NUMBER = 4;
    private java.lang.String negativeText_;
    /**
     * <code>optional string negative_text = 4;</code>
     * @return Whether the negativeText field is set.
     */
    @java.lang.Override
    public boolean hasNegativeText() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>optional string negative_text = 4;</code>
     * @return The negativeText.
     */
    @java.lang.Override
    public java.lang.String getNegativeText() {
      return negativeText_;
    }
    /**
     * <code>optional string negative_text = 4;</code>
     * @return The bytes for negativeText.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNegativeTextBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(negativeText_);
    }
    /**
     * <code>optional string negative_text = 4;</code>
     * @param value The negativeText to set.
     */
    private void setNegativeText(
        java.lang.String value) {
      value.getClass();
  bitField0_ |= 0x00000008;
      negativeText_ = value;
    }
    /**
     * <code>optional string negative_text = 4;</code>
     */
    private void clearNegativeText() {
      bitField0_ = (bitField0_ & ~0x00000008);
      negativeText_ = getDefaultInstance().getNegativeText();
    }
    /**
     * <code>optional string negative_text = 4;</code>
     * @param value The bytes for negativeText to set.
     */
    private void setNegativeTextBytes(
        com.google.protobuf.ByteString value) {
      negativeText_ = value.toStringUtf8();
      bitField0_ |= 0x00000008;
    }

    public static final int CLICKTHROUGH_URL_FIELD_NUMBER = 5;
    private java.lang.String clickthroughUrl_;
    /**
     * <pre>
     * The url to present when user did choose to clickthrough.
     * </pre>
     *
     * <code>optional string clickthrough_url = 5;</code>
     * @return Whether the clickthroughUrl field is set.
     */
    @java.lang.Override
    public boolean hasClickthroughUrl() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <pre>
     * The url to present when user did choose to clickthrough.
     * </pre>
     *
     * <code>optional string clickthrough_url = 5;</code>
     * @return The clickthroughUrl.
     */
    @java.lang.Override
    public java.lang.String getClickthroughUrl() {
      return clickthroughUrl_;
    }
    /**
     * <pre>
     * The url to present when user did choose to clickthrough.
     * </pre>
     *
     * <code>optional string clickthrough_url = 5;</code>
     * @return The bytes for clickthroughUrl.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getClickthroughUrlBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(clickthroughUrl_);
    }
    /**
     * <pre>
     * The url to present when user did choose to clickthrough.
     * </pre>
     *
     * <code>optional string clickthrough_url = 5;</code>
     * @param value The clickthroughUrl to set.
     */
    private void setClickthroughUrl(
        java.lang.String value) {
      value.getClass();
  bitField0_ |= 0x00000010;
      clickthroughUrl_ = value;
    }
    /**
     * <pre>
     * The url to present when user did choose to clickthrough.
     * </pre>
     *
     * <code>optional string clickthrough_url = 5;</code>
     */
    private void clearClickthroughUrl() {
      bitField0_ = (bitField0_ & ~0x00000010);
      clickthroughUrl_ = getDefaultInstance().getClickthroughUrl();
    }
    /**
     * <pre>
     * The url to present when user did choose to clickthrough.
     * </pre>
     *
     * <code>optional string clickthrough_url = 5;</code>
     * @param value The bytes for clickthroughUrl to set.
     */
    private void setClickthroughUrlBytes(
        com.google.protobuf.ByteString value) {
      clickthroughUrl_ = value.toStringUtf8();
      bitField0_ |= 0x00000010;
    }

    public static org.chromium.chrome.browser.autofill_assistant.proto.DetailsProto.ImageClickthroughData parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static org.chromium.chrome.browser.autofill_assistant.proto.DetailsProto.ImageClickthroughData parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static org.chromium.chrome.browser.autofill_assistant.proto.DetailsProto.ImageClickthroughData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static org.chromium.chrome.browser.autofill_assistant.proto.DetailsProto.ImageClickthroughData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static org.chromium.chrome.browser.autofill_assistant.proto.DetailsProto.ImageClickthroughData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static org.chromium.chrome.browser.autofill_assistant.proto.DetailsProto.ImageClickthroughData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static org.chromium.chrome.browser.autofill_assistant.proto.DetailsProto.ImageClickthroughData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static org.chromium.chrome.browser.autofill_assistant.proto.DetailsProto.ImageClickthroughData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static org.chromium.chrome.browser.autofill_assistant.proto.DetailsProto.ImageClickthroughData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static org.chromium.chrome.browser.autofill_assistant.proto.DetailsProto.ImageClickthroughData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static org.chromium.chrome.browser.autofill_assistant.proto.DetailsProto.ImageClickthroughData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static org.chromium.chrome.browser.autofill_assistant.proto.DetailsProto.ImageClickthroughData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(org.chromium.chrome.browser.autofill_assistant.proto.DetailsProto.ImageClickthroughData prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * <pre>
     * Specifies what happens when user tap on the image in the details section.
     * </pre>
     *
     * Protobuf type {@code autofill_assistant.DetailsProto.ImageClickthroughData}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          org.chromium.chrome.browser.autofill_assistant.proto.DetailsProto.ImageClickthroughData, Builder> implements
        // @@protoc_insertion_point(builder_implements:autofill_assistant.DetailsProto.ImageClickthroughData)
        org.chromium.chrome.browser.autofill_assistant.proto.DetailsProto.ImageClickthroughDataOrBuilder {
      // Construct using org.chromium.chrome.browser.autofill_assistant.proto.DetailsProto.ImageClickthroughData.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <pre>
       * Whether to show the original URL where image is extracted from. Only
       * useful when 'image_url' is set.
       * </pre>
       *
       * <code>optional bool allow_clickthrough = 1;</code>
       * @return Whether the allowClickthrough field is set.
       */
      @java.lang.Override
      public boolean hasAllowClickthrough() {
        return instance.hasAllowClickthrough();
      }
      /**
       * <pre>
       * Whether to show the original URL where image is extracted from. Only
       * useful when 'image_url' is set.
       * </pre>
       *
       * <code>optional bool allow_clickthrough = 1;</code>
       * @return The allowClickthrough.
       */
      @java.lang.Override
      public boolean getAllowClickthrough() {
        return instance.getAllowClickthrough();
      }
      /**
       * <pre>
       * Whether to show the original URL where image is extracted from. Only
       * useful when 'image_url' is set.
       * </pre>
       *
       * <code>optional bool allow_clickthrough = 1;</code>
       * @param value The allowClickthrough to set.
       * @return This builder for chaining.
       */
      public Builder setAllowClickthrough(boolean value) {
        copyOnWrite();
        instance.setAllowClickthrough(value);
        return this;
      }
      /**
       * <pre>
       * Whether to show the original URL where image is extracted from. Only
       * useful when 'image_url' is set.
       * </pre>
       *
       * <code>optional bool allow_clickthrough = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearAllowClickthrough() {
        copyOnWrite();
        instance.clearAllowClickthrough();
        return this;
      }

      /**
       * <pre>
       * When image clickthrough is allowed, below texts are used to customize the
       * modal dialog shown to user *if* they are set, otherwise default texts
       * will be used.
       * </pre>
       *
       * <code>optional string description = 2;</code>
       * @return Whether the description field is set.
       */
      @java.lang.Override
      public boolean hasDescription() {
        return instance.hasDescription();
      }
      /**
       * <pre>
       * When image clickthrough is allowed, below texts are used to customize the
       * modal dialog shown to user *if* they are set, otherwise default texts
       * will be used.
       * </pre>
       *
       * <code>optional string description = 2;</code>
       * @return The description.
       */
      @java.lang.Override
      public java.lang.String getDescription() {
        return instance.getDescription();
      }
      /**
       * <pre>
       * When image clickthrough is allowed, below texts are used to customize the
       * modal dialog shown to user *if* they are set, otherwise default texts
       * will be used.
       * </pre>
       *
       * <code>optional string description = 2;</code>
       * @return The bytes for description.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getDescriptionBytes() {
        return instance.getDescriptionBytes();
      }
      /**
       * <pre>
       * When image clickthrough is allowed, below texts are used to customize the
       * modal dialog shown to user *if* they are set, otherwise default texts
       * will be used.
       * </pre>
       *
       * <code>optional string description = 2;</code>
       * @param value The description to set.
       * @return This builder for chaining.
       */
      public Builder setDescription(
          java.lang.String value) {
        copyOnWrite();
        instance.setDescription(value);
        return this;
      }
      /**
       * <pre>
       * When image clickthrough is allowed, below texts are used to customize the
       * modal dialog shown to user *if* they are set, otherwise default texts
       * will be used.
       * </pre>
       *
       * <code>optional string description = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearDescription() {
        copyOnWrite();
        instance.clearDescription();
        return this;
      }
      /**
       * <pre>
       * When image clickthrough is allowed, below texts are used to customize the
       * modal dialog shown to user *if* they are set, otherwise default texts
       * will be used.
       * </pre>
       *
       * <code>optional string description = 2;</code>
       * @param value The bytes for description to set.
       * @return This builder for chaining.
       */
      public Builder setDescriptionBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setDescriptionBytes(value);
        return this;
      }

      /**
       * <code>optional string positive_text = 3;</code>
       * @return Whether the positiveText field is set.
       */
      @java.lang.Override
      public boolean hasPositiveText() {
        return instance.hasPositiveText();
      }
      /**
       * <code>optional string positive_text = 3;</code>
       * @return The positiveText.
       */
      @java.lang.Override
      public java.lang.String getPositiveText() {
        return instance.getPositiveText();
      }
      /**
       * <code>optional string positive_text = 3;</code>
       * @return The bytes for positiveText.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getPositiveTextBytes() {
        return instance.getPositiveTextBytes();
      }
      /**
       * <code>optional string positive_text = 3;</code>
       * @param value The positiveText to set.
       * @return This builder for chaining.
       */
      public Builder setPositiveText(
          java.lang.String value) {
        copyOnWrite();
        instance.setPositiveText(value);
        return this;
      }
      /**
       * <code>optional string positive_text = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearPositiveText() {
        copyOnWrite();
        instance.clearPositiveText();
        return this;
      }
      /**
       * <code>optional string positive_text = 3;</code>
       * @param value The bytes for positiveText to set.
       * @return This builder for chaining.
       */
      public Builder setPositiveTextBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setPositiveTextBytes(value);
        return this;
      }

      /**
       * <code>optional string negative_text = 4;</code>
       * @return Whether the negativeText field is set.
       */
      @java.lang.Override
      public boolean hasNegativeText() {
        return instance.hasNegativeText();
      }
      /**
       * <code>optional string negative_text = 4;</code>
       * @return The negativeText.
       */
      @java.lang.Override
      public java.lang.String getNegativeText() {
        return instance.getNegativeText();
      }
      /**
       * <code>optional string negative_text = 4;</code>
       * @return The bytes for negativeText.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getNegativeTextBytes() {
        return instance.getNegativeTextBytes();
      }
      /**
       * <code>optional string negative_text = 4;</code>
       * @param value The negativeText to set.
       * @return This builder for chaining.
       */
      public Builder setNegativeText(
          java.lang.String value) {
        copyOnWrite();
        instance.setNegativeText(value);
        return this;
      }
      /**
       * <code>optional string negative_text = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearNegativeText() {
        copyOnWrite();
        instance.clearNegativeText();
        return this;
      }
      /**
       * <code>optional string negative_text = 4;</code>
       * @param value The bytes for negativeText to set.
       * @return This builder for chaining.
       */
      public Builder setNegativeTextBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setNegativeTextBytes(value);
        return this;
      }

      /**
       * <pre>
       * The url to present when user did choose to clickthrough.
       * </pre>
       *
       * <code>optional string clickthrough_url = 5;</code>
       * @return Whether the clickthroughUrl field is set.
       */
      @java.lang.Override
      public boolean hasClickthroughUrl() {
        return instance.hasClickthroughUrl();
      }
      /**
       * <pre>
       * The url to present when user did choose to clickthrough.
       * </pre>
       *
       * <code>optional string clickthrough_url = 5;</code>
       * @return The clickthroughUrl.
       */
      @java.lang.Override
      public java.lang.String getClickthroughUrl() {
        return instance.getClickthroughUrl();
      }
      /**
       * <pre>
       * The url to present when user did choose to clickthrough.
       * </pre>
       *
       * <code>optional string clickthrough_url = 5;</code>
       * @return The bytes for clickthroughUrl.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getClickthroughUrlBytes() {
        return instance.getClickthroughUrlBytes();
      }
      /**
       * <pre>
       * The url to present when user did choose to clickthrough.
       * </pre>
       *
       * <code>optional string clickthrough_url = 5;</code>
       * @param value The clickthroughUrl to set.
       * @return This builder for chaining.
       */
      public Builder setClickthroughUrl(
          java.lang.String value) {
        copyOnWrite();
        instance.setClickthroughUrl(value);
        return this;
      }
      /**
       * <pre>
       * The url to present when user did choose to clickthrough.
       * </pre>
       *
       * <code>optional string clickthrough_url = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearClickthroughUrl() {
        copyOnWrite();
        instance.clearClickthroughUrl();
        return this;
      }
      /**
       * <pre>
       * The url to present when user did choose to clickthrough.
       * </pre>
       *
       * <code>optional string clickthrough_url = 5;</code>
       * @param value The bytes for clickthroughUrl to set.
       * @return This builder for chaining.
       */
      public Builder setClickthroughUrlBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setClickthroughUrlBytes(value);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:autofill_assistant.DetailsProto.ImageClickthroughData)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new org.chromium.chrome.browser.autofill_assistant.proto.DetailsProto.ImageClickthroughData();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "bitField0_",
              "allowClickthrough_",
              "description_",
              "positiveText_",
              "negativeText_",
              "clickthroughUrl_",
            };
            java.lang.String info =
                "\u0001\u0005\u0000\u0001\u0001\u0005\u0005\u0000\u0000\u0000\u0001\u1007\u0000\u0002" +
                "\u1008\u0001\u0003\u1008\u0002\u0004\u1008\u0003\u0005\u1008\u0004";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<org.chromium.chrome.browser.autofill_assistant.proto.DetailsProto.ImageClickthroughData> parser = PARSER;
          if (parser == null) {
            synchronized (org.chromium.chrome.browser.autofill_assistant.proto.DetailsProto.ImageClickthroughData.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<org.chromium.chrome.browser.autofill_assistant.proto.DetailsProto.ImageClickthroughData>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:autofill_assistant.DetailsProto.ImageClickthroughData)
    private static final org.chromium.chrome.browser.autofill_assistant.proto.DetailsProto.ImageClickthroughData DEFAULT_INSTANCE;
    static {
      ImageClickthroughData defaultInstance = new ImageClickthroughData();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        ImageClickthroughData.class, defaultInstance);
    }

    public static org.chromium.chrome.browser.autofill_assistant.proto.DetailsProto.ImageClickthroughData getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<ImageClickthroughData> PARSER;

    public static com.google.protobuf.Parser<ImageClickthroughData> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  private int bitField0_;
  private int imageCase_ = 0;
  private java.lang.Object image_;
  public enum ImageCase {
    IMAGE_URL(2),
    SHOW_IMAGE_PLACEHOLDER(10),
    IMAGE_NOT_SET(0);
    private final int value;
    private ImageCase(int value) {
      this.value = value;
    }
    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static ImageCase valueOf(int value) {
      return forNumber(value);
    }

    public static ImageCase forNumber(int value) {
      switch (value) {
        case 2: return IMAGE_URL;
        case 10: return SHOW_IMAGE_PLACEHOLDER;
        case 0: return IMAGE_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  @java.lang.Override
  public ImageCase
  getImageCase() {
    return ImageCase.forNumber(
        imageCase_);
  }

  private void clearImage() {
    imageCase_ = 0;
    image_ = null;
  }

  public static final int TITLE_FIELD_NUMBER = 1;
  private java.lang.String title_;
  /**
   * <code>optional string title = 1;</code>
   * @return Whether the title field is set.
   */
  @java.lang.Override
  public boolean hasTitle() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>optional string title = 1;</code>
   * @return The title.
   */
  @java.lang.Override
  public java.lang.String getTitle() {
    return title_;
  }
  /**
   * <code>optional string title = 1;</code>
   * @return The bytes for title.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTitleBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(title_);
  }
  /**
   * <code>optional string title = 1;</code>
   * @param value The title to set.
   */
  private void setTitle(
      java.lang.String value) {
    value.getClass();
  bitField0_ |= 0x00000001;
    title_ = value;
  }
  /**
   * <code>optional string title = 1;</code>
   */
  private void clearTitle() {
    bitField0_ = (bitField0_ & ~0x00000001);
    title_ = getDefaultInstance().getTitle();
  }
  /**
   * <code>optional string title = 1;</code>
   * @param value The bytes for title to set.
   */
  private void setTitleBytes(
      com.google.protobuf.ByteString value) {
    title_ = value.toStringUtf8();
    bitField0_ |= 0x00000001;
  }

  public static final int IMAGE_URL_FIELD_NUMBER = 2;
  /**
   * <code>string image_url = 2;</code>
   * @return Whether the imageUrl field is set.
   */
  @java.lang.Override
  public boolean hasImageUrl() {
    return imageCase_ == 2;
  }
  /**
   * <code>string image_url = 2;</code>
   * @return The imageUrl.
   */
  @java.lang.Override
  public java.lang.String getImageUrl() {
    java.lang.String ref = "";
    if (imageCase_ == 2) {
      ref = (java.lang.String) image_;
    }
    return ref;
  }
  /**
   * <code>string image_url = 2;</code>
   * @return The bytes for imageUrl.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getImageUrlBytes() {
    java.lang.String ref = "";
    if (imageCase_ == 2) {
      ref = (java.lang.String) image_;
    }
    return com.google.protobuf.ByteString.copyFromUtf8(ref);
  }
  /**
   * <code>string image_url = 2;</code>
   * @param value The imageUrl to set.
   */
  private void setImageUrl(
      java.lang.String value) {
    value.getClass();
  imageCase_ = 2;
    image_ = value;
  }
  /**
   * <code>string image_url = 2;</code>
   */
  private void clearImageUrl() {
    if (imageCase_ == 2) {
      imageCase_ = 0;
      image_ = null;
    }
  }
  /**
   * <code>string image_url = 2;</code>
   * @param value The bytes for imageUrl to set.
   */
  private void setImageUrlBytes(
      com.google.protobuf.ByteString value) {
    image_ = value.toStringUtf8();
    imageCase_ = 2;
  }

  public static final int SHOW_IMAGE_PLACEHOLDER_FIELD_NUMBER = 10;
  /**
   * <pre>
   * When set to true shows placeholder in place of an image.
   * </pre>
   *
   * <code>bool show_image_placeholder = 10;</code>
   * @return Whether the showImagePlaceholder field is set.
   */
  @java.lang.Override
  public boolean hasShowImagePlaceholder() {
    return imageCase_ == 10;
  }
  /**
   * <pre>
   * When set to true shows placeholder in place of an image.
   * </pre>
   *
   * <code>bool show_image_placeholder = 10;</code>
   * @return The showImagePlaceholder.
   */
  @java.lang.Override
  public boolean getShowImagePlaceholder() {
    if (imageCase_ == 10) {
      return (java.lang.Boolean) image_;
    }
    return false;
  }
  /**
   * <pre>
   * When set to true shows placeholder in place of an image.
   * </pre>
   *
   * <code>bool show_image_placeholder = 10;</code>
   * @param value The showImagePlaceholder to set.
   */
  private void setShowImagePlaceholder(boolean value) {
    imageCase_ = 10;
    image_ = value;
  }
  /**
   * <pre>
   * When set to true shows placeholder in place of an image.
   * </pre>
   *
   * <code>bool show_image_placeholder = 10;</code>
   */
  private void clearShowImagePlaceholder() {
    if (imageCase_ == 10) {
      imageCase_ = 0;
      image_ = null;
    }
  }

  public static final int IMAGE_ACCESSIBILITY_HINT_FIELD_NUMBER = 14;
  private java.lang.String imageAccessibilityHint_;
  /**
   * <pre>
   * Specifies the hint for accessibility. If set to empty, the image will not
   * be announced by accessibility.
   * </pre>
   *
   * <code>optional string image_accessibility_hint = 14;</code>
   * @return Whether the imageAccessibilityHint field is set.
   */
  @java.lang.Override
  public boolean hasImageAccessibilityHint() {
    return ((bitField0_ & 0x00000008) != 0);
  }
  /**
   * <pre>
   * Specifies the hint for accessibility. If set to empty, the image will not
   * be announced by accessibility.
   * </pre>
   *
   * <code>optional string image_accessibility_hint = 14;</code>
   * @return The imageAccessibilityHint.
   */
  @java.lang.Override
  public java.lang.String getImageAccessibilityHint() {
    return imageAccessibilityHint_;
  }
  /**
   * <pre>
   * Specifies the hint for accessibility. If set to empty, the image will not
   * be announced by accessibility.
   * </pre>
   *
   * <code>optional string image_accessibility_hint = 14;</code>
   * @return The bytes for imageAccessibilityHint.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getImageAccessibilityHintBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(imageAccessibilityHint_);
  }
  /**
   * <pre>
   * Specifies the hint for accessibility. If set to empty, the image will not
   * be announced by accessibility.
   * </pre>
   *
   * <code>optional string image_accessibility_hint = 14;</code>
   * @param value The imageAccessibilityHint to set.
   */
  private void setImageAccessibilityHint(
      java.lang.String value) {
    value.getClass();
  bitField0_ |= 0x00000008;
    imageAccessibilityHint_ = value;
  }
  /**
   * <pre>
   * Specifies the hint for accessibility. If set to empty, the image will not
   * be announced by accessibility.
   * </pre>
   *
   * <code>optional string image_accessibility_hint = 14;</code>
   */
  private void clearImageAccessibilityHint() {
    bitField0_ = (bitField0_ & ~0x00000008);
    imageAccessibilityHint_ = getDefaultInstance().getImageAccessibilityHint();
  }
  /**
   * <pre>
   * Specifies the hint for accessibility. If set to empty, the image will not
   * be announced by accessibility.
   * </pre>
   *
   * <code>optional string image_accessibility_hint = 14;</code>
   * @param value The bytes for imageAccessibilityHint to set.
   */
  private void setImageAccessibilityHintBytes(
      com.google.protobuf.ByteString value) {
    imageAccessibilityHint_ = value.toStringUtf8();
    bitField0_ |= 0x00000008;
  }

  public static final int IMAGE_CLICKTHROUGH_DATA_FIELD_NUMBER = 12;
  private org.chromium.chrome.browser.autofill_assistant.proto.DetailsProto.ImageClickthroughData imageClickthroughData_;
  /**
   * <code>optional .autofill_assistant.DetailsProto.ImageClickthroughData image_clickthrough_data = 12;</code>
   */
  @java.lang.Override
  public boolean hasImageClickthroughData() {
    return ((bitField0_ & 0x00000010) != 0);
  }
  /**
   * <code>optional .autofill_assistant.DetailsProto.ImageClickthroughData image_clickthrough_data = 12;</code>
   */
  @java.lang.Override
  public org.chromium.chrome.browser.autofill_assistant.proto.DetailsProto.ImageClickthroughData getImageClickthroughData() {
    return imageClickthroughData_ == null ? org.chromium.chrome.browser.autofill_assistant.proto.DetailsProto.ImageClickthroughData.getDefaultInstance() : imageClickthroughData_;
  }
  /**
   * <code>optional .autofill_assistant.DetailsProto.ImageClickthroughData image_clickthrough_data = 12;</code>
   */
  private void setImageClickthroughData(org.chromium.chrome.browser.autofill_assistant.proto.DetailsProto.ImageClickthroughData value) {
    value.getClass();
  imageClickthroughData_ = value;
    bitField0_ |= 0x00000010;
    }
  /**
   * <code>optional .autofill_assistant.DetailsProto.ImageClickthroughData image_clickthrough_data = 12;</code>
   */
  @java.lang.SuppressWarnings({"ReferenceEquality"})
  private void mergeImageClickthroughData(org.chromium.chrome.browser.autofill_assistant.proto.DetailsProto.ImageClickthroughData value) {
    value.getClass();
  if (imageClickthroughData_ != null &&
        imageClickthroughData_ != org.chromium.chrome.browser.autofill_assistant.proto.DetailsProto.ImageClickthroughData.getDefaultInstance()) {
      imageClickthroughData_ =
        org.chromium.chrome.browser.autofill_assistant.proto.DetailsProto.ImageClickthroughData.newBuilder(imageClickthroughData_).mergeFrom(value).buildPartial();
    } else {
      imageClickthroughData_ = value;
    }
    bitField0_ |= 0x00000010;
  }
  /**
   * <code>optional .autofill_assistant.DetailsProto.ImageClickthroughData image_clickthrough_data = 12;</code>
   */
  private void clearImageClickthroughData() {  imageClickthroughData_ = null;
    bitField0_ = (bitField0_ & ~0x00000010);
  }

  public static final int TOTAL_PRICE_LABEL_FIELD_NUMBER = 9;
  private java.lang.String totalPriceLabel_;
  /**
   * <pre>
   * Optional label to provide additional price information.
   * </pre>
   *
   * <code>optional string total_price_label = 9;</code>
   * @return Whether the totalPriceLabel field is set.
   */
  @java.lang.Override
  public boolean hasTotalPriceLabel() {
    return ((bitField0_ & 0x00000020) != 0);
  }
  /**
   * <pre>
   * Optional label to provide additional price information.
   * </pre>
   *
   * <code>optional string total_price_label = 9;</code>
   * @return The totalPriceLabel.
   */
  @java.lang.Override
  public java.lang.String getTotalPriceLabel() {
    return totalPriceLabel_;
  }
  /**
   * <pre>
   * Optional label to provide additional price information.
   * </pre>
   *
   * <code>optional string total_price_label = 9;</code>
   * @return The bytes for totalPriceLabel.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTotalPriceLabelBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(totalPriceLabel_);
  }
  /**
   * <pre>
   * Optional label to provide additional price information.
   * </pre>
   *
   * <code>optional string total_price_label = 9;</code>
   * @param value The totalPriceLabel to set.
   */
  private void setTotalPriceLabel(
      java.lang.String value) {
    value.getClass();
  bitField0_ |= 0x00000020;
    totalPriceLabel_ = value;
  }
  /**
   * <pre>
   * Optional label to provide additional price information.
   * </pre>
   *
   * <code>optional string total_price_label = 9;</code>
   */
  private void clearTotalPriceLabel() {
    bitField0_ = (bitField0_ & ~0x00000020);
    totalPriceLabel_ = getDefaultInstance().getTotalPriceLabel();
  }
  /**
   * <pre>
   * Optional label to provide additional price information.
   * </pre>
   *
   * <code>optional string total_price_label = 9;</code>
   * @param value The bytes for totalPriceLabel to set.
   */
  private void setTotalPriceLabelBytes(
      com.google.protobuf.ByteString value) {
    totalPriceLabel_ = value.toStringUtf8();
    bitField0_ |= 0x00000020;
  }

  public static final int TOTAL_PRICE_FIELD_NUMBER = 6;
  private java.lang.String totalPrice_;
  /**
   * <pre>
   * The price containing the total amount and the currency to pay, formatted
   * in the client's locale (e.g., $123.00).
   * </pre>
   *
   * <code>optional string total_price = 6;</code>
   * @return Whether the totalPrice field is set.
   */
  @java.lang.Override
  public boolean hasTotalPrice() {
    return ((bitField0_ & 0x00000040) != 0);
  }
  /**
   * <pre>
   * The price containing the total amount and the currency to pay, formatted
   * in the client's locale (e.g., $123.00).
   * </pre>
   *
   * <code>optional string total_price = 6;</code>
   * @return The totalPrice.
   */
  @java.lang.Override
  public java.lang.String getTotalPrice() {
    return totalPrice_;
  }
  /**
   * <pre>
   * The price containing the total amount and the currency to pay, formatted
   * in the client's locale (e.g., $123.00).
   * </pre>
   *
   * <code>optional string total_price = 6;</code>
   * @return The bytes for totalPrice.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTotalPriceBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(totalPrice_);
  }
  /**
   * <pre>
   * The price containing the total amount and the currency to pay, formatted
   * in the client's locale (e.g., $123.00).
   * </pre>
   *
   * <code>optional string total_price = 6;</code>
   * @param value The totalPrice to set.
   */
  private void setTotalPrice(
      java.lang.String value) {
    value.getClass();
  bitField0_ |= 0x00000040;
    totalPrice_ = value;
  }
  /**
   * <pre>
   * The price containing the total amount and the currency to pay, formatted
   * in the client's locale (e.g., $123.00).
   * </pre>
   *
   * <code>optional string total_price = 6;</code>
   */
  private void clearTotalPrice() {
    bitField0_ = (bitField0_ & ~0x00000040);
    totalPrice_ = getDefaultInstance().getTotalPrice();
  }
  /**
   * <pre>
   * The price containing the total amount and the currency to pay, formatted
   * in the client's locale (e.g., $123.00).
   * </pre>
   *
   * <code>optional string total_price = 6;</code>
   * @param value The bytes for totalPrice to set.
   */
  private void setTotalPriceBytes(
      com.google.protobuf.ByteString value) {
    totalPrice_ = value.toStringUtf8();
    bitField0_ |= 0x00000040;
  }

  public static final int DESCRIPTION_LINE_1_FIELD_NUMBER = 7;
  private java.lang.String descriptionLine1_;
  /**
   * <code>optional string description_line_1 = 7;</code>
   * @return Whether the descriptionLine1 field is set.
   */
  @java.lang.Override
  public boolean hasDescriptionLine1() {
    return ((bitField0_ & 0x00000080) != 0);
  }
  /**
   * <code>optional string description_line_1 = 7;</code>
   * @return The descriptionLine1.
   */
  @java.lang.Override
  public java.lang.String getDescriptionLine1() {
    return descriptionLine1_;
  }
  /**
   * <code>optional string description_line_1 = 7;</code>
   * @return The bytes for descriptionLine1.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDescriptionLine1Bytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(descriptionLine1_);
  }
  /**
   * <code>optional string description_line_1 = 7;</code>
   * @param value The descriptionLine1 to set.
   */
  private void setDescriptionLine1(
      java.lang.String value) {
    value.getClass();
  bitField0_ |= 0x00000080;
    descriptionLine1_ = value;
  }
  /**
   * <code>optional string description_line_1 = 7;</code>
   */
  private void clearDescriptionLine1() {
    bitField0_ = (bitField0_ & ~0x00000080);
    descriptionLine1_ = getDefaultInstance().getDescriptionLine1();
  }
  /**
   * <code>optional string description_line_1 = 7;</code>
   * @param value The bytes for descriptionLine1 to set.
   */
  private void setDescriptionLine1Bytes(
      com.google.protobuf.ByteString value) {
    descriptionLine1_ = value.toStringUtf8();
    bitField0_ |= 0x00000080;
  }

  public static final int DESCRIPTION_LINE_2_FIELD_NUMBER = 8;
  private java.lang.String descriptionLine2_;
  /**
   * <code>optional string description_line_2 = 8;</code>
   * @return Whether the descriptionLine2 field is set.
   */
  @java.lang.Override
  public boolean hasDescriptionLine2() {
    return ((bitField0_ & 0x00000100) != 0);
  }
  /**
   * <code>optional string description_line_2 = 8;</code>
   * @return The descriptionLine2.
   */
  @java.lang.Override
  public java.lang.String getDescriptionLine2() {
    return descriptionLine2_;
  }
  /**
   * <code>optional string description_line_2 = 8;</code>
   * @return The bytes for descriptionLine2.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDescriptionLine2Bytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(descriptionLine2_);
  }
  /**
   * <code>optional string description_line_2 = 8;</code>
   * @param value The descriptionLine2 to set.
   */
  private void setDescriptionLine2(
      java.lang.String value) {
    value.getClass();
  bitField0_ |= 0x00000100;
    descriptionLine2_ = value;
  }
  /**
   * <code>optional string description_line_2 = 8;</code>
   */
  private void clearDescriptionLine2() {
    bitField0_ = (bitField0_ & ~0x00000100);
    descriptionLine2_ = getDefaultInstance().getDescriptionLine2();
  }
  /**
   * <code>optional string description_line_2 = 8;</code>
   * @param value The bytes for descriptionLine2 to set.
   */
  private void setDescriptionLine2Bytes(
      com.google.protobuf.ByteString value) {
    descriptionLine2_ = value.toStringUtf8();
    bitField0_ |= 0x00000100;
  }

  public static final int DESCRIPTION_LINE_3_FIELD_NUMBER = 13;
  private java.lang.String descriptionLine3_;
  /**
   * <code>optional string description_line_3 = 13;</code>
   * @return Whether the descriptionLine3 field is set.
   */
  @java.lang.Override
  public boolean hasDescriptionLine3() {
    return ((bitField0_ & 0x00000200) != 0);
  }
  /**
   * <code>optional string description_line_3 = 13;</code>
   * @return The descriptionLine3.
   */
  @java.lang.Override
  public java.lang.String getDescriptionLine3() {
    return descriptionLine3_;
  }
  /**
   * <code>optional string description_line_3 = 13;</code>
   * @return The bytes for descriptionLine3.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDescriptionLine3Bytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(descriptionLine3_);
  }
  /**
   * <code>optional string description_line_3 = 13;</code>
   * @param value The descriptionLine3 to set.
   */
  private void setDescriptionLine3(
      java.lang.String value) {
    value.getClass();
  bitField0_ |= 0x00000200;
    descriptionLine3_ = value;
  }
  /**
   * <code>optional string description_line_3 = 13;</code>
   */
  private void clearDescriptionLine3() {
    bitField0_ = (bitField0_ & ~0x00000200);
    descriptionLine3_ = getDefaultInstance().getDescriptionLine3();
  }
  /**
   * <code>optional string description_line_3 = 13;</code>
   * @param value The bytes for descriptionLine3 to set.
   */
  private void setDescriptionLine3Bytes(
      com.google.protobuf.ByteString value) {
    descriptionLine3_ = value.toStringUtf8();
    bitField0_ |= 0x00000200;
  }

  public static final int DATETIME_FIELD_NUMBER = 3;
  private org.chromium.chrome.browser.autofill_assistant.proto.DateTimeProto datetime_;
  /**
   * <pre>
   * Deprecated, but currently still necessary and supported. We can get rid of
   * these fields when the backend starts setting description_line_1 and 2.
   * </pre>
   *
   * <code>optional .autofill_assistant.DateTimeProto datetime = 3;</code>
   */
  @java.lang.Override
  public boolean hasDatetime() {
    return ((bitField0_ & 0x00000400) != 0);
  }
  /**
   * <pre>
   * Deprecated, but currently still necessary and supported. We can get rid of
   * these fields when the backend starts setting description_line_1 and 2.
   * </pre>
   *
   * <code>optional .autofill_assistant.DateTimeProto datetime = 3;</code>
   */
  @java.lang.Override
  public org.chromium.chrome.browser.autofill_assistant.proto.DateTimeProto getDatetime() {
    return datetime_ == null ? org.chromium.chrome.browser.autofill_assistant.proto.DateTimeProto.getDefaultInstance() : datetime_;
  }
  /**
   * <pre>
   * Deprecated, but currently still necessary and supported. We can get rid of
   * these fields when the backend starts setting description_line_1 and 2.
   * </pre>
   *
   * <code>optional .autofill_assistant.DateTimeProto datetime = 3;</code>
   */
  private void setDatetime(org.chromium.chrome.browser.autofill_assistant.proto.DateTimeProto value) {
    value.getClass();
  datetime_ = value;
    bitField0_ |= 0x00000400;
    }
  /**
   * <pre>
   * Deprecated, but currently still necessary and supported. We can get rid of
   * these fields when the backend starts setting description_line_1 and 2.
   * </pre>
   *
   * <code>optional .autofill_assistant.DateTimeProto datetime = 3;</code>
   */
  @java.lang.SuppressWarnings({"ReferenceEquality"})
  private void mergeDatetime(org.chromium.chrome.browser.autofill_assistant.proto.DateTimeProto value) {
    value.getClass();
  if (datetime_ != null &&
        datetime_ != org.chromium.chrome.browser.autofill_assistant.proto.DateTimeProto.getDefaultInstance()) {
      datetime_ =
        org.chromium.chrome.browser.autofill_assistant.proto.DateTimeProto.newBuilder(datetime_).mergeFrom(value).buildPartial();
    } else {
      datetime_ = value;
    }
    bitField0_ |= 0x00000400;
  }
  /**
   * <pre>
   * Deprecated, but currently still necessary and supported. We can get rid of
   * these fields when the backend starts setting description_line_1 and 2.
   * </pre>
   *
   * <code>optional .autofill_assistant.DateTimeProto datetime = 3;</code>
   */
  private void clearDatetime() {  datetime_ = null;
    bitField0_ = (bitField0_ & ~0x00000400);
  }

  public static final int DESCRIPTION_FIELD_NUMBER = 4;
  private java.lang.String description_;
  /**
   * <code>optional string description = 4;</code>
   * @return Whether the description field is set.
   */
  @java.lang.Override
  public boolean hasDescription() {
    return ((bitField0_ & 0x00000800) != 0);
  }
  /**
   * <code>optional string description = 4;</code>
   * @return The description.
   */
  @java.lang.Override
  public java.lang.String getDescription() {
    return description_;
  }
  /**
   * <code>optional string description = 4;</code>
   * @return The bytes for description.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDescriptionBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(description_);
  }
  /**
   * <code>optional string description = 4;</code>
   * @param value The description to set.
   */
  private void setDescription(
      java.lang.String value) {
    value.getClass();
  bitField0_ |= 0x00000800;
    description_ = value;
  }
  /**
   * <code>optional string description = 4;</code>
   */
  private void clearDescription() {
    bitField0_ = (bitField0_ & ~0x00000800);
    description_ = getDefaultInstance().getDescription();
  }
  /**
   * <code>optional string description = 4;</code>
   * @param value The bytes for description to set.
   */
  private void setDescriptionBytes(
      com.google.protobuf.ByteString value) {
    description_ = value.toStringUtf8();
    bitField0_ |= 0x00000800;
  }

  public static final int ANIMATE_PLACEHOLDERS_FIELD_NUMBER = 11;
  private boolean animatePlaceholders_;
  /**
   * <pre>
   * Asks the UI to show animated placeholders for missing fields.
   * The placeholder will be shown on effectively missing:
   * * title
   * * image
   * * description line (1, 2 or 3)
   * TODO(crbug.com/806868): Make the fields for displaying placeholders
   * configurable by the server.
   * </pre>
   *
   * <code>optional bool animate_placeholders = 11;</code>
   * @return Whether the animatePlaceholders field is set.
   */
  @java.lang.Override
  public boolean hasAnimatePlaceholders() {
    return ((bitField0_ & 0x00001000) != 0);
  }
  /**
   * <pre>
   * Asks the UI to show animated placeholders for missing fields.
   * The placeholder will be shown on effectively missing:
   * * title
   * * image
   * * description line (1, 2 or 3)
   * TODO(crbug.com/806868): Make the fields for displaying placeholders
   * configurable by the server.
   * </pre>
   *
   * <code>optional bool animate_placeholders = 11;</code>
   * @return The animatePlaceholders.
   */
  @java.lang.Override
  public boolean getAnimatePlaceholders() {
    return animatePlaceholders_;
  }
  /**
   * <pre>
   * Asks the UI to show animated placeholders for missing fields.
   * The placeholder will be shown on effectively missing:
   * * title
   * * image
   * * description line (1, 2 or 3)
   * TODO(crbug.com/806868): Make the fields for displaying placeholders
   * configurable by the server.
   * </pre>
   *
   * <code>optional bool animate_placeholders = 11;</code>
   * @param value The animatePlaceholders to set.
   */
  private void setAnimatePlaceholders(boolean value) {
    bitField0_ |= 0x00001000;
    animatePlaceholders_ = value;
  }
  /**
   * <pre>
   * Asks the UI to show animated placeholders for missing fields.
   * The placeholder will be shown on effectively missing:
   * * title
   * * image
   * * description line (1, 2 or 3)
   * TODO(crbug.com/806868): Make the fields for displaying placeholders
   * configurable by the server.
   * </pre>
   *
   * <code>optional bool animate_placeholders = 11;</code>
   */
  private void clearAnimatePlaceholders() {
    bitField0_ = (bitField0_ & ~0x00001000);
    animatePlaceholders_ = false;
  }

  public static org.chromium.chrome.browser.autofill_assistant.proto.DetailsProto parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static org.chromium.chrome.browser.autofill_assistant.proto.DetailsProto parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static org.chromium.chrome.browser.autofill_assistant.proto.DetailsProto parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static org.chromium.chrome.browser.autofill_assistant.proto.DetailsProto parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static org.chromium.chrome.browser.autofill_assistant.proto.DetailsProto parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static org.chromium.chrome.browser.autofill_assistant.proto.DetailsProto parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static org.chromium.chrome.browser.autofill_assistant.proto.DetailsProto parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static org.chromium.chrome.browser.autofill_assistant.proto.DetailsProto parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static org.chromium.chrome.browser.autofill_assistant.proto.DetailsProto parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static org.chromium.chrome.browser.autofill_assistant.proto.DetailsProto parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static org.chromium.chrome.browser.autofill_assistant.proto.DetailsProto parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static org.chromium.chrome.browser.autofill_assistant.proto.DetailsProto parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(org.chromium.chrome.browser.autofill_assistant.proto.DetailsProto prototype) {
    return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code autofill_assistant.DetailsProto}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        org.chromium.chrome.browser.autofill_assistant.proto.DetailsProto, Builder> implements
      // @@protoc_insertion_point(builder_implements:autofill_assistant.DetailsProto)
      org.chromium.chrome.browser.autofill_assistant.proto.DetailsProtoOrBuilder {
    // Construct using org.chromium.chrome.browser.autofill_assistant.proto.DetailsProto.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }

    @java.lang.Override
    public ImageCase
        getImageCase() {
      return instance.getImageCase();
    }

    public Builder clearImage() {
      copyOnWrite();
      instance.clearImage();
      return this;
    }


    /**
     * <code>optional string title = 1;</code>
     * @return Whether the title field is set.
     */
    @java.lang.Override
    public boolean hasTitle() {
      return instance.hasTitle();
    }
    /**
     * <code>optional string title = 1;</code>
     * @return The title.
     */
    @java.lang.Override
    public java.lang.String getTitle() {
      return instance.getTitle();
    }
    /**
     * <code>optional string title = 1;</code>
     * @return The bytes for title.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTitleBytes() {
      return instance.getTitleBytes();
    }
    /**
     * <code>optional string title = 1;</code>
     * @param value The title to set.
     * @return This builder for chaining.
     */
    public Builder setTitle(
        java.lang.String value) {
      copyOnWrite();
      instance.setTitle(value);
      return this;
    }
    /**
     * <code>optional string title = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearTitle() {
      copyOnWrite();
      instance.clearTitle();
      return this;
    }
    /**
     * <code>optional string title = 1;</code>
     * @param value The bytes for title to set.
     * @return This builder for chaining.
     */
    public Builder setTitleBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setTitleBytes(value);
      return this;
    }

    /**
     * <code>string image_url = 2;</code>
     * @return Whether the imageUrl field is set.
     */
    @java.lang.Override
    public boolean hasImageUrl() {
      return instance.hasImageUrl();
    }
    /**
     * <code>string image_url = 2;</code>
     * @return The imageUrl.
     */
    @java.lang.Override
    public java.lang.String getImageUrl() {
      return instance.getImageUrl();
    }
    /**
     * <code>string image_url = 2;</code>
     * @return The bytes for imageUrl.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getImageUrlBytes() {
      return instance.getImageUrlBytes();
    }
    /**
     * <code>string image_url = 2;</code>
     * @param value The imageUrl to set.
     * @return This builder for chaining.
     */
    public Builder setImageUrl(
        java.lang.String value) {
      copyOnWrite();
      instance.setImageUrl(value);
      return this;
    }
    /**
     * <code>string image_url = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearImageUrl() {
      copyOnWrite();
      instance.clearImageUrl();
      return this;
    }
    /**
     * <code>string image_url = 2;</code>
     * @param value The bytes for imageUrl to set.
     * @return This builder for chaining.
     */
    public Builder setImageUrlBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setImageUrlBytes(value);
      return this;
    }

    /**
     * <pre>
     * When set to true shows placeholder in place of an image.
     * </pre>
     *
     * <code>bool show_image_placeholder = 10;</code>
     * @return Whether the showImagePlaceholder field is set.
     */
    @java.lang.Override
    public boolean hasShowImagePlaceholder() {
      return instance.hasShowImagePlaceholder();
    }
    /**
     * <pre>
     * When set to true shows placeholder in place of an image.
     * </pre>
     *
     * <code>bool show_image_placeholder = 10;</code>
     * @return The showImagePlaceholder.
     */
    @java.lang.Override
    public boolean getShowImagePlaceholder() {
      return instance.getShowImagePlaceholder();
    }
    /**
     * <pre>
     * When set to true shows placeholder in place of an image.
     * </pre>
     *
     * <code>bool show_image_placeholder = 10;</code>
     * @param value The showImagePlaceholder to set.
     * @return This builder for chaining.
     */
    public Builder setShowImagePlaceholder(boolean value) {
      copyOnWrite();
      instance.setShowImagePlaceholder(value);
      return this;
    }
    /**
     * <pre>
     * When set to true shows placeholder in place of an image.
     * </pre>
     *
     * <code>bool show_image_placeholder = 10;</code>
     * @return This builder for chaining.
     */
    public Builder clearShowImagePlaceholder() {
      copyOnWrite();
      instance.clearShowImagePlaceholder();
      return this;
    }

    /**
     * <pre>
     * Specifies the hint for accessibility. If set to empty, the image will not
     * be announced by accessibility.
     * </pre>
     *
     * <code>optional string image_accessibility_hint = 14;</code>
     * @return Whether the imageAccessibilityHint field is set.
     */
    @java.lang.Override
    public boolean hasImageAccessibilityHint() {
      return instance.hasImageAccessibilityHint();
    }
    /**
     * <pre>
     * Specifies the hint for accessibility. If set to empty, the image will not
     * be announced by accessibility.
     * </pre>
     *
     * <code>optional string image_accessibility_hint = 14;</code>
     * @return The imageAccessibilityHint.
     */
    @java.lang.Override
    public java.lang.String getImageAccessibilityHint() {
      return instance.getImageAccessibilityHint();
    }
    /**
     * <pre>
     * Specifies the hint for accessibility. If set to empty, the image will not
     * be announced by accessibility.
     * </pre>
     *
     * <code>optional string image_accessibility_hint = 14;</code>
     * @return The bytes for imageAccessibilityHint.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getImageAccessibilityHintBytes() {
      return instance.getImageAccessibilityHintBytes();
    }
    /**
     * <pre>
     * Specifies the hint for accessibility. If set to empty, the image will not
     * be announced by accessibility.
     * </pre>
     *
     * <code>optional string image_accessibility_hint = 14;</code>
     * @param value The imageAccessibilityHint to set.
     * @return This builder for chaining.
     */
    public Builder setImageAccessibilityHint(
        java.lang.String value) {
      copyOnWrite();
      instance.setImageAccessibilityHint(value);
      return this;
    }
    /**
     * <pre>
     * Specifies the hint for accessibility. If set to empty, the image will not
     * be announced by accessibility.
     * </pre>
     *
     * <code>optional string image_accessibility_hint = 14;</code>
     * @return This builder for chaining.
     */
    public Builder clearImageAccessibilityHint() {
      copyOnWrite();
      instance.clearImageAccessibilityHint();
      return this;
    }
    /**
     * <pre>
     * Specifies the hint for accessibility. If set to empty, the image will not
     * be announced by accessibility.
     * </pre>
     *
     * <code>optional string image_accessibility_hint = 14;</code>
     * @param value The bytes for imageAccessibilityHint to set.
     * @return This builder for chaining.
     */
    public Builder setImageAccessibilityHintBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setImageAccessibilityHintBytes(value);
      return this;
    }

    /**
     * <code>optional .autofill_assistant.DetailsProto.ImageClickthroughData image_clickthrough_data = 12;</code>
     */
    @java.lang.Override
    public boolean hasImageClickthroughData() {
      return instance.hasImageClickthroughData();
    }
    /**
     * <code>optional .autofill_assistant.DetailsProto.ImageClickthroughData image_clickthrough_data = 12;</code>
     */
    @java.lang.Override
    public org.chromium.chrome.browser.autofill_assistant.proto.DetailsProto.ImageClickthroughData getImageClickthroughData() {
      return instance.getImageClickthroughData();
    }
    /**
     * <code>optional .autofill_assistant.DetailsProto.ImageClickthroughData image_clickthrough_data = 12;</code>
     */
    public Builder setImageClickthroughData(org.chromium.chrome.browser.autofill_assistant.proto.DetailsProto.ImageClickthroughData value) {
      copyOnWrite();
      instance.setImageClickthroughData(value);
      return this;
      }
    /**
     * <code>optional .autofill_assistant.DetailsProto.ImageClickthroughData image_clickthrough_data = 12;</code>
     */
    public Builder setImageClickthroughData(
        org.chromium.chrome.browser.autofill_assistant.proto.DetailsProto.ImageClickthroughData.Builder builderForValue) {
      copyOnWrite();
      instance.setImageClickthroughData(builderForValue.build());
      return this;
    }
    /**
     * <code>optional .autofill_assistant.DetailsProto.ImageClickthroughData image_clickthrough_data = 12;</code>
     */
    public Builder mergeImageClickthroughData(org.chromium.chrome.browser.autofill_assistant.proto.DetailsProto.ImageClickthroughData value) {
      copyOnWrite();
      instance.mergeImageClickthroughData(value);
      return this;
    }
    /**
     * <code>optional .autofill_assistant.DetailsProto.ImageClickthroughData image_clickthrough_data = 12;</code>
     */
    public Builder clearImageClickthroughData() {  copyOnWrite();
      instance.clearImageClickthroughData();
      return this;
    }

    /**
     * <pre>
     * Optional label to provide additional price information.
     * </pre>
     *
     * <code>optional string total_price_label = 9;</code>
     * @return Whether the totalPriceLabel field is set.
     */
    @java.lang.Override
    public boolean hasTotalPriceLabel() {
      return instance.hasTotalPriceLabel();
    }
    /**
     * <pre>
     * Optional label to provide additional price information.
     * </pre>
     *
     * <code>optional string total_price_label = 9;</code>
     * @return The totalPriceLabel.
     */
    @java.lang.Override
    public java.lang.String getTotalPriceLabel() {
      return instance.getTotalPriceLabel();
    }
    /**
     * <pre>
     * Optional label to provide additional price information.
     * </pre>
     *
     * <code>optional string total_price_label = 9;</code>
     * @return The bytes for totalPriceLabel.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTotalPriceLabelBytes() {
      return instance.getTotalPriceLabelBytes();
    }
    /**
     * <pre>
     * Optional label to provide additional price information.
     * </pre>
     *
     * <code>optional string total_price_label = 9;</code>
     * @param value The totalPriceLabel to set.
     * @return This builder for chaining.
     */
    public Builder setTotalPriceLabel(
        java.lang.String value) {
      copyOnWrite();
      instance.setTotalPriceLabel(value);
      return this;
    }
    /**
     * <pre>
     * Optional label to provide additional price information.
     * </pre>
     *
     * <code>optional string total_price_label = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearTotalPriceLabel() {
      copyOnWrite();
      instance.clearTotalPriceLabel();
      return this;
    }
    /**
     * <pre>
     * Optional label to provide additional price information.
     * </pre>
     *
     * <code>optional string total_price_label = 9;</code>
     * @param value The bytes for totalPriceLabel to set.
     * @return This builder for chaining.
     */
    public Builder setTotalPriceLabelBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setTotalPriceLabelBytes(value);
      return this;
    }

    /**
     * <pre>
     * The price containing the total amount and the currency to pay, formatted
     * in the client's locale (e.g., $123.00).
     * </pre>
     *
     * <code>optional string total_price = 6;</code>
     * @return Whether the totalPrice field is set.
     */
    @java.lang.Override
    public boolean hasTotalPrice() {
      return instance.hasTotalPrice();
    }
    /**
     * <pre>
     * The price containing the total amount and the currency to pay, formatted
     * in the client's locale (e.g., $123.00).
     * </pre>
     *
     * <code>optional string total_price = 6;</code>
     * @return The totalPrice.
     */
    @java.lang.Override
    public java.lang.String getTotalPrice() {
      return instance.getTotalPrice();
    }
    /**
     * <pre>
     * The price containing the total amount and the currency to pay, formatted
     * in the client's locale (e.g., $123.00).
     * </pre>
     *
     * <code>optional string total_price = 6;</code>
     * @return The bytes for totalPrice.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTotalPriceBytes() {
      return instance.getTotalPriceBytes();
    }
    /**
     * <pre>
     * The price containing the total amount and the currency to pay, formatted
     * in the client's locale (e.g., $123.00).
     * </pre>
     *
     * <code>optional string total_price = 6;</code>
     * @param value The totalPrice to set.
     * @return This builder for chaining.
     */
    public Builder setTotalPrice(
        java.lang.String value) {
      copyOnWrite();
      instance.setTotalPrice(value);
      return this;
    }
    /**
     * <pre>
     * The price containing the total amount and the currency to pay, formatted
     * in the client's locale (e.g., $123.00).
     * </pre>
     *
     * <code>optional string total_price = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearTotalPrice() {
      copyOnWrite();
      instance.clearTotalPrice();
      return this;
    }
    /**
     * <pre>
     * The price containing the total amount and the currency to pay, formatted
     * in the client's locale (e.g., $123.00).
     * </pre>
     *
     * <code>optional string total_price = 6;</code>
     * @param value The bytes for totalPrice to set.
     * @return This builder for chaining.
     */
    public Builder setTotalPriceBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setTotalPriceBytes(value);
      return this;
    }

    /**
     * <code>optional string description_line_1 = 7;</code>
     * @return Whether the descriptionLine1 field is set.
     */
    @java.lang.Override
    public boolean hasDescriptionLine1() {
      return instance.hasDescriptionLine1();
    }
    /**
     * <code>optional string description_line_1 = 7;</code>
     * @return The descriptionLine1.
     */
    @java.lang.Override
    public java.lang.String getDescriptionLine1() {
      return instance.getDescriptionLine1();
    }
    /**
     * <code>optional string description_line_1 = 7;</code>
     * @return The bytes for descriptionLine1.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getDescriptionLine1Bytes() {
      return instance.getDescriptionLine1Bytes();
    }
    /**
     * <code>optional string description_line_1 = 7;</code>
     * @param value The descriptionLine1 to set.
     * @return This builder for chaining.
     */
    public Builder setDescriptionLine1(
        java.lang.String value) {
      copyOnWrite();
      instance.setDescriptionLine1(value);
      return this;
    }
    /**
     * <code>optional string description_line_1 = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearDescriptionLine1() {
      copyOnWrite();
      instance.clearDescriptionLine1();
      return this;
    }
    /**
     * <code>optional string description_line_1 = 7;</code>
     * @param value The bytes for descriptionLine1 to set.
     * @return This builder for chaining.
     */
    public Builder setDescriptionLine1Bytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setDescriptionLine1Bytes(value);
      return this;
    }

    /**
     * <code>optional string description_line_2 = 8;</code>
     * @return Whether the descriptionLine2 field is set.
     */
    @java.lang.Override
    public boolean hasDescriptionLine2() {
      return instance.hasDescriptionLine2();
    }
    /**
     * <code>optional string description_line_2 = 8;</code>
     * @return The descriptionLine2.
     */
    @java.lang.Override
    public java.lang.String getDescriptionLine2() {
      return instance.getDescriptionLine2();
    }
    /**
     * <code>optional string description_line_2 = 8;</code>
     * @return The bytes for descriptionLine2.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getDescriptionLine2Bytes() {
      return instance.getDescriptionLine2Bytes();
    }
    /**
     * <code>optional string description_line_2 = 8;</code>
     * @param value The descriptionLine2 to set.
     * @return This builder for chaining.
     */
    public Builder setDescriptionLine2(
        java.lang.String value) {
      copyOnWrite();
      instance.setDescriptionLine2(value);
      return this;
    }
    /**
     * <code>optional string description_line_2 = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearDescriptionLine2() {
      copyOnWrite();
      instance.clearDescriptionLine2();
      return this;
    }
    /**
     * <code>optional string description_line_2 = 8;</code>
     * @param value The bytes for descriptionLine2 to set.
     * @return This builder for chaining.
     */
    public Builder setDescriptionLine2Bytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setDescriptionLine2Bytes(value);
      return this;
    }

    /**
     * <code>optional string description_line_3 = 13;</code>
     * @return Whether the descriptionLine3 field is set.
     */
    @java.lang.Override
    public boolean hasDescriptionLine3() {
      return instance.hasDescriptionLine3();
    }
    /**
     * <code>optional string description_line_3 = 13;</code>
     * @return The descriptionLine3.
     */
    @java.lang.Override
    public java.lang.String getDescriptionLine3() {
      return instance.getDescriptionLine3();
    }
    /**
     * <code>optional string description_line_3 = 13;</code>
     * @return The bytes for descriptionLine3.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getDescriptionLine3Bytes() {
      return instance.getDescriptionLine3Bytes();
    }
    /**
     * <code>optional string description_line_3 = 13;</code>
     * @param value The descriptionLine3 to set.
     * @return This builder for chaining.
     */
    public Builder setDescriptionLine3(
        java.lang.String value) {
      copyOnWrite();
      instance.setDescriptionLine3(value);
      return this;
    }
    /**
     * <code>optional string description_line_3 = 13;</code>
     * @return This builder for chaining.
     */
    public Builder clearDescriptionLine3() {
      copyOnWrite();
      instance.clearDescriptionLine3();
      return this;
    }
    /**
     * <code>optional string description_line_3 = 13;</code>
     * @param value The bytes for descriptionLine3 to set.
     * @return This builder for chaining.
     */
    public Builder setDescriptionLine3Bytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setDescriptionLine3Bytes(value);
      return this;
    }

    /**
     * <pre>
     * Deprecated, but currently still necessary and supported. We can get rid of
     * these fields when the backend starts setting description_line_1 and 2.
     * </pre>
     *
     * <code>optional .autofill_assistant.DateTimeProto datetime = 3;</code>
     */
    @java.lang.Override
    public boolean hasDatetime() {
      return instance.hasDatetime();
    }
    /**
     * <pre>
     * Deprecated, but currently still necessary and supported. We can get rid of
     * these fields when the backend starts setting description_line_1 and 2.
     * </pre>
     *
     * <code>optional .autofill_assistant.DateTimeProto datetime = 3;</code>
     */
    @java.lang.Override
    public org.chromium.chrome.browser.autofill_assistant.proto.DateTimeProto getDatetime() {
      return instance.getDatetime();
    }
    /**
     * <pre>
     * Deprecated, but currently still necessary and supported. We can get rid of
     * these fields when the backend starts setting description_line_1 and 2.
     * </pre>
     *
     * <code>optional .autofill_assistant.DateTimeProto datetime = 3;</code>
     */
    public Builder setDatetime(org.chromium.chrome.browser.autofill_assistant.proto.DateTimeProto value) {
      copyOnWrite();
      instance.setDatetime(value);
      return this;
      }
    /**
     * <pre>
     * Deprecated, but currently still necessary and supported. We can get rid of
     * these fields when the backend starts setting description_line_1 and 2.
     * </pre>
     *
     * <code>optional .autofill_assistant.DateTimeProto datetime = 3;</code>
     */
    public Builder setDatetime(
        org.chromium.chrome.browser.autofill_assistant.proto.DateTimeProto.Builder builderForValue) {
      copyOnWrite();
      instance.setDatetime(builderForValue.build());
      return this;
    }
    /**
     * <pre>
     * Deprecated, but currently still necessary and supported. We can get rid of
     * these fields when the backend starts setting description_line_1 and 2.
     * </pre>
     *
     * <code>optional .autofill_assistant.DateTimeProto datetime = 3;</code>
     */
    public Builder mergeDatetime(org.chromium.chrome.browser.autofill_assistant.proto.DateTimeProto value) {
      copyOnWrite();
      instance.mergeDatetime(value);
      return this;
    }
    /**
     * <pre>
     * Deprecated, but currently still necessary and supported. We can get rid of
     * these fields when the backend starts setting description_line_1 and 2.
     * </pre>
     *
     * <code>optional .autofill_assistant.DateTimeProto datetime = 3;</code>
     */
    public Builder clearDatetime() {  copyOnWrite();
      instance.clearDatetime();
      return this;
    }

    /**
     * <code>optional string description = 4;</code>
     * @return Whether the description field is set.
     */
    @java.lang.Override
    public boolean hasDescription() {
      return instance.hasDescription();
    }
    /**
     * <code>optional string description = 4;</code>
     * @return The description.
     */
    @java.lang.Override
    public java.lang.String getDescription() {
      return instance.getDescription();
    }
    /**
     * <code>optional string description = 4;</code>
     * @return The bytes for description.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getDescriptionBytes() {
      return instance.getDescriptionBytes();
    }
    /**
     * <code>optional string description = 4;</code>
     * @param value The description to set.
     * @return This builder for chaining.
     */
    public Builder setDescription(
        java.lang.String value) {
      copyOnWrite();
      instance.setDescription(value);
      return this;
    }
    /**
     * <code>optional string description = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearDescription() {
      copyOnWrite();
      instance.clearDescription();
      return this;
    }
    /**
     * <code>optional string description = 4;</code>
     * @param value The bytes for description to set.
     * @return This builder for chaining.
     */
    public Builder setDescriptionBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setDescriptionBytes(value);
      return this;
    }

    /**
     * <pre>
     * Asks the UI to show animated placeholders for missing fields.
     * The placeholder will be shown on effectively missing:
     * * title
     * * image
     * * description line (1, 2 or 3)
     * TODO(crbug.com/806868): Make the fields for displaying placeholders
     * configurable by the server.
     * </pre>
     *
     * <code>optional bool animate_placeholders = 11;</code>
     * @return Whether the animatePlaceholders field is set.
     */
    @java.lang.Override
    public boolean hasAnimatePlaceholders() {
      return instance.hasAnimatePlaceholders();
    }
    /**
     * <pre>
     * Asks the UI to show animated placeholders for missing fields.
     * The placeholder will be shown on effectively missing:
     * * title
     * * image
     * * description line (1, 2 or 3)
     * TODO(crbug.com/806868): Make the fields for displaying placeholders
     * configurable by the server.
     * </pre>
     *
     * <code>optional bool animate_placeholders = 11;</code>
     * @return The animatePlaceholders.
     */
    @java.lang.Override
    public boolean getAnimatePlaceholders() {
      return instance.getAnimatePlaceholders();
    }
    /**
     * <pre>
     * Asks the UI to show animated placeholders for missing fields.
     * The placeholder will be shown on effectively missing:
     * * title
     * * image
     * * description line (1, 2 or 3)
     * TODO(crbug.com/806868): Make the fields for displaying placeholders
     * configurable by the server.
     * </pre>
     *
     * <code>optional bool animate_placeholders = 11;</code>
     * @param value The animatePlaceholders to set.
     * @return This builder for chaining.
     */
    public Builder setAnimatePlaceholders(boolean value) {
      copyOnWrite();
      instance.setAnimatePlaceholders(value);
      return this;
    }
    /**
     * <pre>
     * Asks the UI to show animated placeholders for missing fields.
     * The placeholder will be shown on effectively missing:
     * * title
     * * image
     * * description line (1, 2 or 3)
     * TODO(crbug.com/806868): Make the fields for displaying placeholders
     * configurable by the server.
     * </pre>
     *
     * <code>optional bool animate_placeholders = 11;</code>
     * @return This builder for chaining.
     */
    public Builder clearAnimatePlaceholders() {
      copyOnWrite();
      instance.clearAnimatePlaceholders();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:autofill_assistant.DetailsProto)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new org.chromium.chrome.browser.autofill_assistant.proto.DetailsProto();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "image_",
            "imageCase_",
            "bitField0_",
            "title_",
            "datetime_",
            "description_",
            "totalPrice_",
            "descriptionLine1_",
            "descriptionLine2_",
            "totalPriceLabel_",
            "animatePlaceholders_",
            "imageClickthroughData_",
            "descriptionLine3_",
            "imageAccessibilityHint_",
          };
          java.lang.String info =
              "\u0001\r\u0001\u0001\u0001\u000e\r\u0000\u0000\u0000\u0001\u1008\u0000\u0002\u103b" +
              "\u0000\u0003\u1009\n\u0004\u1008\u000b\u0006\u1008\u0006\u0007\u1008\u0007\b\u1008" +
              "\b\t\u1008\u0005\n\u103a\u0000\u000b\u1007\f\f\u1009\u0004\r\u1008\t\u000e\u1008" +
              "\u0003";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<org.chromium.chrome.browser.autofill_assistant.proto.DetailsProto> parser = PARSER;
        if (parser == null) {
          synchronized (org.chromium.chrome.browser.autofill_assistant.proto.DetailsProto.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<org.chromium.chrome.browser.autofill_assistant.proto.DetailsProto>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:autofill_assistant.DetailsProto)
  private static final org.chromium.chrome.browser.autofill_assistant.proto.DetailsProto DEFAULT_INSTANCE;
  static {
    DetailsProto defaultInstance = new DetailsProto();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      DetailsProto.class, defaultInstance);
  }

  public static org.chromium.chrome.browser.autofill_assistant.proto.DetailsProto getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<DetailsProto> PARSER;

  public static com.google.protobuf.Parser<DetailsProto> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

