// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: view_layout.proto

package org.chromium.chrome.browser.autofill_assistant.proto;

/**
 * Protobuf type {@code autofill_assistant.ImageViewProto}
 */
public  final class ImageViewProto extends
    com.google.protobuf.GeneratedMessageLite<
        ImageViewProto, ImageViewProto.Builder> implements
    // @@protoc_insertion_point(message_implements:autofill_assistant.ImageViewProto)
    ImageViewProtoOrBuilder {
  private ImageViewProto() {
  }
  private int bitField0_;
  public static final int IMAGE_FIELD_NUMBER = 1;
  private org.chromium.chrome.browser.autofill_assistant.proto.DrawableProto image_;
  /**
   * <code>optional .autofill_assistant.DrawableProto image = 1;</code>
   */
  @java.lang.Override
  public boolean hasImage() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>optional .autofill_assistant.DrawableProto image = 1;</code>
   */
  @java.lang.Override
  public org.chromium.chrome.browser.autofill_assistant.proto.DrawableProto getImage() {
    return image_ == null ? org.chromium.chrome.browser.autofill_assistant.proto.DrawableProto.getDefaultInstance() : image_;
  }
  /**
   * <code>optional .autofill_assistant.DrawableProto image = 1;</code>
   */
  private void setImage(org.chromium.chrome.browser.autofill_assistant.proto.DrawableProto value) {
    value.getClass();
  image_ = value;
    bitField0_ |= 0x00000001;
    }
  /**
   * <code>optional .autofill_assistant.DrawableProto image = 1;</code>
   */
  @java.lang.SuppressWarnings({"ReferenceEquality"})
  private void mergeImage(org.chromium.chrome.browser.autofill_assistant.proto.DrawableProto value) {
    value.getClass();
  if (image_ != null &&
        image_ != org.chromium.chrome.browser.autofill_assistant.proto.DrawableProto.getDefaultInstance()) {
      image_ =
        org.chromium.chrome.browser.autofill_assistant.proto.DrawableProto.newBuilder(image_).mergeFrom(value).buildPartial();
    } else {
      image_ = value;
    }
    bitField0_ |= 0x00000001;
  }
  /**
   * <code>optional .autofill_assistant.DrawableProto image = 1;</code>
   */
  private void clearImage() {  image_ = null;
    bitField0_ = (bitField0_ & ~0x00000001);
  }

  public static org.chromium.chrome.browser.autofill_assistant.proto.ImageViewProto parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static org.chromium.chrome.browser.autofill_assistant.proto.ImageViewProto parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static org.chromium.chrome.browser.autofill_assistant.proto.ImageViewProto parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static org.chromium.chrome.browser.autofill_assistant.proto.ImageViewProto parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static org.chromium.chrome.browser.autofill_assistant.proto.ImageViewProto parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static org.chromium.chrome.browser.autofill_assistant.proto.ImageViewProto parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static org.chromium.chrome.browser.autofill_assistant.proto.ImageViewProto parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static org.chromium.chrome.browser.autofill_assistant.proto.ImageViewProto parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static org.chromium.chrome.browser.autofill_assistant.proto.ImageViewProto parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static org.chromium.chrome.browser.autofill_assistant.proto.ImageViewProto parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static org.chromium.chrome.browser.autofill_assistant.proto.ImageViewProto parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static org.chromium.chrome.browser.autofill_assistant.proto.ImageViewProto parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(org.chromium.chrome.browser.autofill_assistant.proto.ImageViewProto prototype) {
    return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code autofill_assistant.ImageViewProto}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        org.chromium.chrome.browser.autofill_assistant.proto.ImageViewProto, Builder> implements
      // @@protoc_insertion_point(builder_implements:autofill_assistant.ImageViewProto)
      org.chromium.chrome.browser.autofill_assistant.proto.ImageViewProtoOrBuilder {
    // Construct using org.chromium.chrome.browser.autofill_assistant.proto.ImageViewProto.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>optional .autofill_assistant.DrawableProto image = 1;</code>
     */
    @java.lang.Override
    public boolean hasImage() {
      return instance.hasImage();
    }
    /**
     * <code>optional .autofill_assistant.DrawableProto image = 1;</code>
     */
    @java.lang.Override
    public org.chromium.chrome.browser.autofill_assistant.proto.DrawableProto getImage() {
      return instance.getImage();
    }
    /**
     * <code>optional .autofill_assistant.DrawableProto image = 1;</code>
     */
    public Builder setImage(org.chromium.chrome.browser.autofill_assistant.proto.DrawableProto value) {
      copyOnWrite();
      instance.setImage(value);
      return this;
      }
    /**
     * <code>optional .autofill_assistant.DrawableProto image = 1;</code>
     */
    public Builder setImage(
        org.chromium.chrome.browser.autofill_assistant.proto.DrawableProto.Builder builderForValue) {
      copyOnWrite();
      instance.setImage(builderForValue.build());
      return this;
    }
    /**
     * <code>optional .autofill_assistant.DrawableProto image = 1;</code>
     */
    public Builder mergeImage(org.chromium.chrome.browser.autofill_assistant.proto.DrawableProto value) {
      copyOnWrite();
      instance.mergeImage(value);
      return this;
    }
    /**
     * <code>optional .autofill_assistant.DrawableProto image = 1;</code>
     */
    public Builder clearImage() {  copyOnWrite();
      instance.clearImage();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:autofill_assistant.ImageViewProto)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new org.chromium.chrome.browser.autofill_assistant.proto.ImageViewProto();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "bitField0_",
            "image_",
          };
          java.lang.String info =
              "\u0001\u0001\u0000\u0001\u0001\u0001\u0001\u0000\u0000\u0000\u0001\u1009\u0000";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<org.chromium.chrome.browser.autofill_assistant.proto.ImageViewProto> parser = PARSER;
        if (parser == null) {
          synchronized (org.chromium.chrome.browser.autofill_assistant.proto.ImageViewProto.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<org.chromium.chrome.browser.autofill_assistant.proto.ImageViewProto>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:autofill_assistant.ImageViewProto)
  private static final org.chromium.chrome.browser.autofill_assistant.proto.ImageViewProto DEFAULT_INSTANCE;
  static {
    ImageViewProto defaultInstance = new ImageViewProto();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      ImageViewProto.class, defaultInstance);
  }

  public static org.chromium.chrome.browser.autofill_assistant.proto.ImageViewProto getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<ImageViewProto> PARSER;

  public static com.google.protobuf.Parser<ImageViewProto> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

