// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: components/sync/protocol/history_status.proto

package org.chromium.components.sync.protocol;

/**
 * <pre>
 * Response to a history status request.
 * </pre>
 *
 * Protobuf type {@code sync_pb.HistoryStatusResponse}
 */
public  final class HistoryStatusResponse extends
    com.google.protobuf.GeneratedMessageLite<
        HistoryStatusResponse, HistoryStatusResponse.Builder> implements
    // @@protoc_insertion_point(message_implements:sync_pb.HistoryStatusResponse)
    HistoryStatusResponseOrBuilder {
  private HistoryStatusResponse() {
    minPollIntervalSeconds_ = 3600;
  }
  private int bitField0_;
  public static final int MIN_POLL_INTERVAL_SECONDS_FIELD_NUMBER = 1;
  private int minPollIntervalSeconds_;
  /**
   * <pre>
   * Minimal time to wait before issuing another request.
   * </pre>
   *
   * <code>optional int32 min_poll_interval_seconds = 1 [default = 3600];</code>
   * @return Whether the minPollIntervalSeconds field is set.
   */
  @java.lang.Override
  public boolean hasMinPollIntervalSeconds() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <pre>
   * Minimal time to wait before issuing another request.
   * </pre>
   *
   * <code>optional int32 min_poll_interval_seconds = 1 [default = 3600];</code>
   * @return The minPollIntervalSeconds.
   */
  @java.lang.Override
  public int getMinPollIntervalSeconds() {
    return minPollIntervalSeconds_;
  }
  /**
   * <pre>
   * Minimal time to wait before issuing another request.
   * </pre>
   *
   * <code>optional int32 min_poll_interval_seconds = 1 [default = 3600];</code>
   * @param value The minPollIntervalSeconds to set.
   */
  private void setMinPollIntervalSeconds(int value) {
    bitField0_ |= 0x00000001;
    minPollIntervalSeconds_ = value;
  }
  /**
   * <pre>
   * Minimal time to wait before issuing another request.
   * </pre>
   *
   * <code>optional int32 min_poll_interval_seconds = 1 [default = 3600];</code>
   */
  private void clearMinPollIntervalSeconds() {
    bitField0_ = (bitField0_ & ~0x00000001);
    minPollIntervalSeconds_ = 3600;
  }

  public static final int HAS_DERIVED_DATA_FIELD_NUMBER = 2;
  private boolean hasDerivedData_;
  /**
   * <pre>
   * Indicates whether the history corpuses have any derived data for a user.
   * </pre>
   *
   * <code>optional bool has_derived_data = 2;</code>
   * @return Whether the hasDerivedData field is set.
   */
  @java.lang.Override
  public boolean hasHasDerivedData() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <pre>
   * Indicates whether the history corpuses have any derived data for a user.
   * </pre>
   *
   * <code>optional bool has_derived_data = 2;</code>
   * @return The hasDerivedData.
   */
  @java.lang.Override
  public boolean getHasDerivedData() {
    return hasDerivedData_;
  }
  /**
   * <pre>
   * Indicates whether the history corpuses have any derived data for a user.
   * </pre>
   *
   * <code>optional bool has_derived_data = 2;</code>
   * @param value The hasDerivedData to set.
   */
  private void setHasDerivedData(boolean value) {
    bitField0_ |= 0x00000002;
    hasDerivedData_ = value;
  }
  /**
   * <pre>
   * Indicates whether the history corpuses have any derived data for a user.
   * </pre>
   *
   * <code>optional bool has_derived_data = 2;</code>
   */
  private void clearHasDerivedData() {
    bitField0_ = (bitField0_ & ~0x00000002);
    hasDerivedData_ = false;
  }

  public static org.chromium.components.sync.protocol.HistoryStatusResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static org.chromium.components.sync.protocol.HistoryStatusResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static org.chromium.components.sync.protocol.HistoryStatusResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static org.chromium.components.sync.protocol.HistoryStatusResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static org.chromium.components.sync.protocol.HistoryStatusResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static org.chromium.components.sync.protocol.HistoryStatusResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static org.chromium.components.sync.protocol.HistoryStatusResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static org.chromium.components.sync.protocol.HistoryStatusResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static org.chromium.components.sync.protocol.HistoryStatusResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static org.chromium.components.sync.protocol.HistoryStatusResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static org.chromium.components.sync.protocol.HistoryStatusResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static org.chromium.components.sync.protocol.HistoryStatusResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(org.chromium.components.sync.protocol.HistoryStatusResponse prototype) {
    return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * <pre>
   * Response to a history status request.
   * </pre>
   *
   * Protobuf type {@code sync_pb.HistoryStatusResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        org.chromium.components.sync.protocol.HistoryStatusResponse, Builder> implements
      // @@protoc_insertion_point(builder_implements:sync_pb.HistoryStatusResponse)
      org.chromium.components.sync.protocol.HistoryStatusResponseOrBuilder {
    // Construct using org.chromium.components.sync.protocol.HistoryStatusResponse.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <pre>
     * Minimal time to wait before issuing another request.
     * </pre>
     *
     * <code>optional int32 min_poll_interval_seconds = 1 [default = 3600];</code>
     * @return Whether the minPollIntervalSeconds field is set.
     */
    @java.lang.Override
    public boolean hasMinPollIntervalSeconds() {
      return instance.hasMinPollIntervalSeconds();
    }
    /**
     * <pre>
     * Minimal time to wait before issuing another request.
     * </pre>
     *
     * <code>optional int32 min_poll_interval_seconds = 1 [default = 3600];</code>
     * @return The minPollIntervalSeconds.
     */
    @java.lang.Override
    public int getMinPollIntervalSeconds() {
      return instance.getMinPollIntervalSeconds();
    }
    /**
     * <pre>
     * Minimal time to wait before issuing another request.
     * </pre>
     *
     * <code>optional int32 min_poll_interval_seconds = 1 [default = 3600];</code>
     * @param value The minPollIntervalSeconds to set.
     * @return This builder for chaining.
     */
    public Builder setMinPollIntervalSeconds(int value) {
      copyOnWrite();
      instance.setMinPollIntervalSeconds(value);
      return this;
    }
    /**
     * <pre>
     * Minimal time to wait before issuing another request.
     * </pre>
     *
     * <code>optional int32 min_poll_interval_seconds = 1 [default = 3600];</code>
     * @return This builder for chaining.
     */
    public Builder clearMinPollIntervalSeconds() {
      copyOnWrite();
      instance.clearMinPollIntervalSeconds();
      return this;
    }

    /**
     * <pre>
     * Indicates whether the history corpuses have any derived data for a user.
     * </pre>
     *
     * <code>optional bool has_derived_data = 2;</code>
     * @return Whether the hasDerivedData field is set.
     */
    @java.lang.Override
    public boolean hasHasDerivedData() {
      return instance.hasHasDerivedData();
    }
    /**
     * <pre>
     * Indicates whether the history corpuses have any derived data for a user.
     * </pre>
     *
     * <code>optional bool has_derived_data = 2;</code>
     * @return The hasDerivedData.
     */
    @java.lang.Override
    public boolean getHasDerivedData() {
      return instance.getHasDerivedData();
    }
    /**
     * <pre>
     * Indicates whether the history corpuses have any derived data for a user.
     * </pre>
     *
     * <code>optional bool has_derived_data = 2;</code>
     * @param value The hasDerivedData to set.
     * @return This builder for chaining.
     */
    public Builder setHasDerivedData(boolean value) {
      copyOnWrite();
      instance.setHasDerivedData(value);
      return this;
    }
    /**
     * <pre>
     * Indicates whether the history corpuses have any derived data for a user.
     * </pre>
     *
     * <code>optional bool has_derived_data = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearHasDerivedData() {
      copyOnWrite();
      instance.clearHasDerivedData();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:sync_pb.HistoryStatusResponse)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new org.chromium.components.sync.protocol.HistoryStatusResponse();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "bitField0_",
            "minPollIntervalSeconds_",
            "hasDerivedData_",
          };
          java.lang.String info =
              "\u0001\u0002\u0000\u0001\u0001\u0002\u0002\u0000\u0000\u0000\u0001\u1004\u0000\u0002" +
              "\u1007\u0001";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<org.chromium.components.sync.protocol.HistoryStatusResponse> parser = PARSER;
        if (parser == null) {
          synchronized (org.chromium.components.sync.protocol.HistoryStatusResponse.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<org.chromium.components.sync.protocol.HistoryStatusResponse>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:sync_pb.HistoryStatusResponse)
  private static final org.chromium.components.sync.protocol.HistoryStatusResponse DEFAULT_INSTANCE;
  static {
    HistoryStatusResponse defaultInstance = new HistoryStatusResponse();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      HistoryStatusResponse.class, defaultInstance);
  }

  public static org.chromium.components.sync.protocol.HistoryStatusResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<HistoryStatusResponse> PARSER;

  public static com.google.protobuf.Parser<HistoryStatusResponse> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

